Premiere exploration des données de Bronchiolite -passage aux urgances

In [24]:
#import des librairies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [ ]:
#pour construire le chemin d'accès aux fichiers de données

from pathlib import Path

raw = Path(r"C:\Users\monik\Documents\3_PRO\3_LEARNING\13_Formation_DATA_SCIENTIST\Projet\Fil_rouge\GitHub\LIORA_PROJET_PATHO_RESPIRATOIRES\notebooks")

print(list(raw.iterdir()))

[WindowsPath('C:/Users/monik/Documents/3_PRO/3_LEARNING/13_Formation_DATA_SCIENTIST/Projet/Fil_rouge/GitHub/LIORA_PROJET_PATHO_RESPIRATOIRES/notebooks/01.Exploration_asthme_MLU.ipynb'), WindowsPath('C:/Users/monik/Documents/3_PRO/3_LEARNING/13_Formation_DATA_SCIENTIST/Projet/Fil_rouge/GitHub/LIORA_PROJET_PATHO_RESPIRATOIRES/notebooks/02.Exploration_allergie_MLU .ipynb'), WindowsPath('C:/Users/monik/Documents/3_PRO/3_LEARNING/13_Formation_DATA_SCIENTIST/Projet/Fil_rouge/GitHub/LIORA_PROJET_PATHO_RESPIRATOIRES/notebooks/03.Exploration_bronchiolite_MLU.ipynb'), WindowsPath('C:/Users/monik/Documents/3_PRO/3_LEARNING/13_Formation_DATA_SCIENTIST/Projet/Fil_rouge/GitHub/LIORA_PROJET_PATHO_RESPIRATOIRES/notebooks/Explo_data_cibles.ipynb'), WindowsPath('C:/Users/monik/Documents/3_PRO/3_LEARNING/13_Formation_DATA_SCIENTIST/Projet/Fil_rouge/GitHub/LIORA_PROJET_PATHO_RESPIRATOIRES/notebooks/Explo_MeteoSynop_MLA.ipynb')]

In [ ]:
#pour construire le chemin d'accès aux fichiers de données

from pathlib import Path

raw = Path("../data/raw")

# Afficher tous les fichiers CSV, y compris dans les sous-dossiers
for fichier in raw.rglob("*.csv"):
    print(fichier)

..\data\raw\Sante\allergie-passages-aux-urgences-et-actes-sos-medecins-dep.csv
..\data\raw\Sante\asthme-passages-aux-urgences-et-actes-sos-medecins-dep.csv
..\data\raw\Sante\bronchiolite-passages-aux-urgences-et-actes-sos-medecins-departement.csv
..\data\raw\Sante\effectifs.csv

In [4]:
df_bronchiolite = pd.read_csv(
    "../data/raw/Sante/bronchiolite-passages-aux-urgences-et-actes-sos-medecins-departement.csv"
)
df_bronchiolite.head()

,1er jour de la semaine,Semaine,Classe d'âge,Taux de passages aux urgences pour bronchiolite,Taux d'hospitalisations après passages aux urgences pour bronchiolite,Taux d'actes médicaux SOS médecins pour bronchiolite,Département Code,Département,Région Code,Région
0,2026-09-28,2026-S40,0 an,14285.714286,NaN,NaN,09,Ariège,76,Occitanie
1,2026-09-28,2026-S40,0 an,0.000000,0.000000,NaN,12,Aveyron,76,Occitanie
2,2026-09-28,2026-S40,0 an,5468.750000,8333.333333,9195.402299,14,Calvados,28,Normandie
3,2026-09-28,2026-S40,0 an,0.000000,0.000000,NaN,01,Ain,84,Auvergne et Rhône-Alpes
4,2026-09-28,2026-S40,0 an,7692.307692,0.000000,NaN,05,Hautes-Alpes,93,Provence-Alpes-Côte d'Azur

In [5]:
#info generale sur le dataframe
df_bronchiolite.info()

<class 'pandas.DataFrame'>
RangeIndex: 36280 entries, 0 to 36279
Data columns (total 10 columns):
 #   Column                                                                 Non-Null Count  Dtype
---  ------                                                                 --------------  -----
 0   1er jour de la semaine                                                 36280 non-null  str
 1   Semaine                                                                36280 non-null  str
 2   Classe d'âge                                                           36280 non-null  str
 3   Taux de passages aux urgences pour bronchiolite                        35282 non-null  float64
 4   Taux d'hospitalisations après passages aux urgences pour bronchiolite  32911 non-null  float64
 5   Taux d'actes médicaux SOS médecins pour bronchiolite                   16081 non-null  float64
 6   Département Code                                                       36280 non-null  str
 7   Département                                                            36280 non-null  str
 8   Région Code                                                            36280 non-null  int64
 9   Région                                                                 36280 non-null  str
dtypes: float64(3), int64(1), str(6)
memory usage: 2.8 MB

In [6]:
#combien de colonne et de lignes
df_bronchiolite.shape

(36280, 10)

Verification la presence des doublons

In [7]:
df_bronchiolite.duplicated()

print(df_bronchiolite.duplicated().sum())

0

Verification des valeurs manquantes

In [8]:
#mesurer les valeurs manquantes : afficher le nombre de valeurs manquantes par colonne
df_bronchiolite.isna().sum()

1er jour de la semaine                                                       0
Semaine                                                                      0
Classe d'âge                                                                 0
Taux de passages aux urgences pour bronchiolite                            998
Taux d'hospitalisations après passages aux urgences pour bronchiolite     3369
Taux d'actes médicaux SOS médecins pour bronchiolite                     20199
Département Code                                                             0
Département                                                                  0
Région Code                                                                  0
Région                                                                       0
dtype: int64

In [9]:
# pourcentage de valeurs manquantes par colonne
df_bronchiolite.isna().mean().mul(100)

1er jour de la semaine                                                    0.000000
Semaine                                                                   0.000000
Classe d'âge                                                              0.000000
Taux de passages aux urgences pour bronchiolite                           2.750827
Taux d'hospitalisations après passages aux urgences pour bronchiolite     9.286108
Taux d'actes médicaux SOS médecins pour bronchiolite                     55.675303
Département Code                                                          0.000000
Département                                                               0.000000
Région Code                                                               0.000000
Région                                                                    0.000000
dtype: float64

In [22]:
#Valeurs uniques par colonnes
colonnes = df_bronchiolite.columns.tolist()
df_bronchiolite[colonnes].nunique()

1er jour de la semaine                                                    353
Semaine                                                                   353
Classe d'âge                                                                1
Taux de passages aux urgences pour bronchiolite                          6341
Taux d'hospitalisations après passages aux urgences pour bronchiolite    1775
Taux d'actes médicaux SOS médecins pour bronchiolite                     1614
Département Code                                                          104
Département                                                               104
Région Code                                                                21
Région                                                                     21
dtype: int64

In [23]:
#quelles sont les valeurs uniques dans la colonne "Classe d'âge"
df_bronchiolite["Classe d'âge"].unique()

<StringArray>
['0 an']
Length: 1, dtype: str

In [14]:
#Statistiques descriptives pour la colonne "Taux de passages aux urgences pour bronchiolite"
df_bronchiolite["Taux de passages aux urgences pour bronchiolite"].describe()

count     35282.000000
mean       9222.219282
std        9298.822367
min           0.000000
25%        2338.273949
50%        6821.164400
75%       13048.797787
max      100000.000000
Name: Taux de passages aux urgences pour bronchiolite, dtype: float64

In [15]:
#Statistiques descriptives pour la colonne "Taux d'hospitalisations après passages aux urgences pour bronchiolite"
df_bronchiolite["Taux d'hospitalisations après passages aux urgences pour bronchiolite"].describe()

count     32911.000000
mean      18354.797667
std       19773.936710
min           0.000000
25%           0.000000
50%       13333.333333
75%       28571.428571
max      100000.000000
Name: Taux d'hospitalisations après passages aux urgences pour bronchiolite, dtype: float64

In [16]:
#Statistiques descriptives pour la colonne "Taux d'actes médicaux SOS médecins pour bronchiolite" 
df_bronchiolite["Taux d'actes médicaux SOS médecins pour bronchiolite"].describe()

count     16081.000000
mean       6061.418464
std        6577.079040
min           0.000000
25%           0.000000
50%        4545.454545
75%        8988.764045
max      100000.000000
Name: Taux d'actes médicaux SOS médecins pour bronchiolite, dtype: float64

In [17]:
#Valeurs manquantes par département pour la colonne "Taux d'actes médicaux SOS médecins pour bronchiolite"
manquant1 = df_bronchiolite["Taux d'actes médicaux SOS médecins pour bronchiolite"].isna()

taux_manquants = (
    manquant1.groupby(df_bronchiolite["Département Code"])
    .mean()*100
)

taux_manquants.sort_values(ascending=False)

Département Code
01    100.0
03    100.0
04    100.0
05    100.0
08    100.0
      ...
73      0.0
75      0.0
76      0.0
89      0.0
91      0.0
Name: Taux d'actes médicaux SOS médecins pour bronchiolite, Length: 104, dtype: float64

In [18]:
#Valeurs manquantes par département pour la colonne "Taux d'hospitalisations après passages aux urgences pour bronchiolite"
manquant2 = df_bronchiolite["Taux d'hospitalisations après passages aux urgences pour bronchiolite"].isna()

taux_manquants = (
    manquant2.groupby(df_bronchiolite["Département Code"])
    .mean()*100
)

taux_manquants.sort_values(ascending=False)

Département Code
978    100.000000
975    100.000000
977    100.000000
23      82.152975
19      58.923513
          ...
92       0.000000
88       0.000000
974      0.000000
971      0.000000
973      0.000000
Name: Taux d'hospitalisations après passages aux urgences pour bronchiolite, Length: 104, dtype: float64

In [19]:
#Valeurs manquantes par département pour la colonne "Taux de passages aux urgences pour bronchiolite"
manquant3 = df_bronchiolite["Taux de passages aux urgences pour bronchiolite"].isna()

taux_manquants = (
    manquant3.groupby(df_bronchiolite   ["Département Code"])
    .mean()*100
)

taux_manquants.sort_values(ascending=False)

Département Code
978    100.000000
975    100.000000
977    100.000000
972     50.424929
53      16.997167
          ...
92       0.000000
974      0.000000
973      0.000000
971      0.000000
976      0.000000
Name: Taux de passages aux urgences pour bronchiolite, Length: 104, dtype: float64

Verification la coherence  des colonnes redondantes

In [20]:
#comparer si "Semaine" correspond à "1er jour de la semaine" pour chaque ligne :
#0 je fais un copie pour pas modifier l'originale df_bronchiolite
df_bronchiolite2 = df_bronchiolite.copy()
# 1. Tranformation de la date en numero de semaine
# nettoyage
df_bronchiolite2.columns = (
    df_bronchiolite2.columns
    .str.replace(" ", "_")
    .str.strip()
)

df_bronchiolite2.info()

#2. Transformation de la colonne "1er_jour_de_la_semaine" en datetime (date impossible devient NaT, valeur manquant)
col_date = "1er_jour_de_la_semaine"

dates = pd.to_datetime(
    df_bronchiolite2[col_date], format="%Y-%m-%d", errors="coerce"
)

#extraire l'année et la semaine de la date
iso = dates.dt.isocalendar()

#reconstruction de la meme format que la colonne "Semaine" : "YYYY-SWW"
semaine_calculee = (
    iso["year"].astype("string")
    + "-S"
    + iso["week"].astype("string").str.zfill(2)
)


semaine_source = df_bronchiolite["Semaine"]

#Verification
valide = (
    semaine_source.notna()                      #La semaine est renseignée
    & dates.notna()                             #La date est present et pu etre convertie  
    & semaine_source.eq(semaine_calculee)       #La semaine correspond à la date
    & dates.dt.dayofweek.eq(0)                  #La date est un lundi (0 = lundi, 1 = mardi, ..., 6 = dimanche)
).fillna(False)

print(f"{valide.sum()} lignes cohérentes sur {len(df_bronchiolite2)}")

<class 'pandas.DataFrame'>
RangeIndex: 36280 entries, 0 to 36279
Data columns (total 10 columns):
 #   Column                                                                 Non-Null Count  Dtype
---  ------                                                                 --------------  -----
 0   1er_jour_de_la_semaine                                                 36280 non-null  str
 1   Semaine                                                                36280 non-null  str
 2   Classe_d'âge                                                           36280 non-null  str
 3   Taux_de_passages_aux_urgences_pour_bronchiolite                        35282 non-null  float64
 4   Taux_d'hospitalisations_après_passages_aux_urgences_pour_bronchiolite  32911 non-null  float64
 5   Taux_d'actes_médicaux_SOS_médecins_pour_bronchiolite                   16081 non-null  float64
 6   Département_Code                                                       36280 non-null  str
 7   Département                                                            36280 non-null  str
 8   Région_Code                                                            36280 non-null  int64
 9   Région                                                                 36280 non-null  str
dtypes: float64(3), int64(1), str(6)
memory usage: 2.8 MB
36280 lignes cohérentes sur 36280

In [ ]:

#comparer si Region correspond à Région Code pour chaque ligne 
    #Est-ce que chaque nom de région possède un seul code ?
    #Est-ce que chaque code possède un seul nom de région ?

#creation tableau de travail
paires = df_bronchiolite2[["Région", "Région_Code"]].copy()

#pour chaque colonne on transforme en texte, retire les espaces et remplace les valeurs vides par NaN si applicable
for col in ["Région", "Région_Code"]:
    paires[col] = (
        paires[col].astype("string").str.strip().replace("", pd.NA)
    )


#Garder les associations distinctes et complètes et on retire les repetitions des lignes entieres pour ne garder que les paires uniques
# Garder une seule fois chaque association région / code
paires = df_bronchiolite2[
    ["Région", "Région_Code"]
].drop_duplicates()

# Chercher les noms associés à plusieurs codes
# ou les codes associés à plusieurs noms
conflits = paires[
    paires.duplicated("Région", keep=False)
    | paires.duplicated("Région_Code", keep=False)
]

display(conflits)

Empty DataFrame
Columns: [Région, Région_Code]
Index: []

In [21]:
#comparer si Département correspond à Département Code pour chaque ligne

    #Est-ce que chaque nom de département possède un seul code ?
    #Est-ce que chaque code possède un seul nom de departement ?

#creation tableau de travail
paires = df_bronchiolite2[["Département", "Département_Code"]].copy()

#pour chaque colonne on transforme en texte, retire les espaces et remplace les valeurs vides par NaN si applicable
for col in ["Département", "Département_Code"]:
    paires[col] = (
        paires[col].astype("string").str.strip().replace("", pd.NA)
    )


#Garder les associations distinctes et complètes et on retire les repetitions des lignes entieres pour ne garder que les paires uniques
# Garder une seule fois chaque association département / code
paires = df_bronchiolite2[
    ["Département", "Département_Code"]
].drop_duplicates()

# Chercher les noms associés à plusieurs codes
# ou les codes associés à plusieurs noms
conflits = paires[
    paires.duplicated("Département", keep=False)
    | paires.duplicated("Département_Code", keep=False)
]

display(conflits)

Empty DataFrame
Columns: [Département, Département_Code]
Index: []

Lignes avec une information manquante : 0
Paires impliquées dans une correspondance ambiguë : 0

Attention! Cela ne garantit pas que les codes sont officiellement corrects. Une mauvaise association répétée partout passerait ce contrôle. La vérification officielle nécessite un référentiel adapté à la période des données.