Premiere exploration des données de Bronchiolite -passage aux urgances

In [1]:
#import des librairies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
#pour construire le chemin d'accès aux fichiers de données

from pathlib import Path

raw = Path(r"C:\Users\monik\Documents\3_PRO\3_LEARNING\13_Formation_DATA_SCIENTIST\Projet\Fil_rouge\GitHub\LIORA_PROJET_PATHO_RESPIRATOIRES\notebooks")

print(list(raw.iterdir()))

[WindowsPath('C:/Users/monik/Documents/3_PRO/3_LEARNING/13_Formation_DATA_SCIENTIST/Projet/Fil_rouge/GitHub/LIORA_PROJET_PATHO_RESPIRATOIRES/notebooks/01.Exploration_asthme_MLU.ipynb'), WindowsPath('C:/Users/monik/Documents/3_PRO/3_LEARNING/13_Formation_DATA_SCIENTIST/Projet/Fil_rouge/GitHub/LIORA_PROJET_PATHO_RESPIRATOIRES/notebooks/02.Exploration_allergie_MLU .ipynb'), WindowsPath('C:/Users/monik/Documents/3_PRO/3_LEARNING/13_Formation_DATA_SCIENTIST/Projet/Fil_rouge/GitHub/LIORA_PROJET_PATHO_RESPIRATOIRES/notebooks/03.Exploration_bronchiolite_MLU.ipynb'), WindowsPath('C:/Users/monik/Documents/3_PRO/3_LEARNING/13_Formation_DATA_SCIENTIST/Projet/Fil_rouge/GitHub/LIORA_PROJET_PATHO_RESPIRATOIRES/notebooks/04.Exploration_effectifs_MLU.ipynb'), WindowsPath('C:/Users/monik/Documents/3_PRO/3_LEARNING/13_Formation_DATA_SCIENTIST/Projet/Fil_rouge/GitHub/LIORA_PROJET_PATHO_RESPIRATOIRES/notebooks/Explo_data_cibles.ipynb'), WindowsPath('C:/Users/monik/Documents/3_PRO/3_LEARNING/13_Formation_DATA_SCIENTIST/Projet/Fil_rouge/GitHub/LIORA_PROJET_PATHO_RESPIRATOIRES/notebooks/Explo_MeteoSynop_MLA.ipynb')]

In [3]:
#pour construire le chemin d'accès aux fichiers de données

from pathlib import Path

raw = Path("../data/raw")

# Afficher tous les fichiers CSV, y compris dans les sous-dossiers
for fichier in raw.rglob("*.csv"):
    print(fichier)

..\data\raw\Sante\allergie-passages-aux-urgences-et-actes-sos-medecins-dep.csv
..\data\raw\Sante\asthme-passages-aux-urgences-et-actes-sos-medecins-dep.csv
..\data\raw\Sante\bronchiolite-passages-aux-urgences-et-actes-sos-medecins-departement.csv
..\data\raw\Sante\effectifs.csv

Info generale: Informations générales :
Les données présentent des informations sur les effectifs de patients pris en charge par l'ensemble des régimes d'assurance maladie. Elles sont disponibles par pathologie, traitement chronique ou épisode de soins, sexe, classe d’âge, région et département.

https://data.ameli.fr/explore/assets/effectifs/

In [5]:
df_effectifs = pd.read_csv(
    "../data/raw/Sante/effectifs.csv", sep=';', 
)
df_effectifs.head()

,annee,patho_niv1,patho_niv2,patho_niv3,top,cla_age_5,sexe,region,dept,Ntop,Npop,prev,Niveau prioritaire,libelle_classe_age,libelle_sexe,tri
0,2020,Maladies psychiatriques,Troubles psychotiques,Troubles psychotiques,PSY_PSC_IND,50-54,2,1,971,280.0,17040,1.643,"2,3",de 50 à 54 ans,femmes,48.0
1,2020,Maladies psychiatriques,Troubles psychotiques,Troubles psychotiques,PSY_PSC_IND,50-54,2,3,999,50.0,6090,0.771,"2,3",de 50 à 54 ans,femmes,48.0
2,2020,Maladies psychiatriques,Troubles psychotiques,Troubles psychotiques,PSY_PSC_IND,50-54,2,4,974,390.0,32630,1.205,"2,3",de 50 à 54 ans,femmes,48.0
3,2020,Maladies psychiatriques,Troubles psychotiques,Troubles psychotiques,PSY_PSC_IND,50-54,2,11,77,350.0,48230,0.732,"2,3",de 50 à 54 ans,femmes,48.0
4,2020,Maladies psychiatriques,Troubles psychotiques,Troubles psychotiques,PSY_PSC_IND,50-54,2,11,91,400.0,43370,0.927,"2,3",de 50 à 54 ans,femmes,48.0

In [6]:
#info generale sur le dataframe
df_effectifs.info()

<class 'pandas.DataFrame'>
RangeIndex: 5796000 entries, 0 to 5795999
Data columns (total 16 columns):
 #   Column              Dtype
---  ------              -----
 0   annee               int64
 1   patho_niv1          str
 2   patho_niv2          str
 3   patho_niv3          str
 4   top                 str
 5   cla_age_5           str
 6   sexe                int64
 7   region              int64
 8   dept                str
 9   Ntop                float64
 10  Npop                int64
 11  prev                float64
 12  Niveau prioritaire  str
 13  libelle_classe_age  str
 14  libelle_sexe        str
 15  tri                 float64
dtypes: float64(3), int64(4), str(9)
memory usage: 707.5 MB

In [7]:
#combien de colonne et de lignes
df_effectifs.shape

(5796000, 16)

Verification la presence des doublons

In [53]:
#reperer les duplicats exactes
df_effectifs.duplicated()

print(df_effectifs.duplicated().sum())

#reperer si il y a une situation qui se repete 
cles = ["annee", "top", "cla_age_5", "sexe", "region", "dept"]

df_effectifs.duplicated(subset=cles).sum()

df_effectifs[
    df_effectifs.duplicated(subset=cles, keep=False)
].sort_values(cles)

0

Empty DataFrame
Columns: [annee, patho_niv1, patho_niv2, patho_niv3, top, cla_age_5, sexe, region, dept, Ntop, Npop, prev, Niveau prioritaire, libelle_classe_age, libelle_sexe, tri]
Index: []

Verification des valeurs manquantes

In [9]:
#mesurer les valeurs manquantes : afficher le nombre de valeurs manquantes par colonne
df_effectifs.isna().sum()

annee                       0
patho_niv1                  0
patho_niv2             604800
patho_niv3            1310400
top                         0
cla_age_5                   0
sexe                        0
region                      0
dept                        0
Ntop                  1526386
Npop                        0
prev                  1526386
Niveau prioritaire      75600
libelle_classe_age          0
libelle_sexe                0
tri                     75600
dtype: int64

In [10]:
# pourcentage de valeurs manquantes par colonne
df_effectifs.isna().mean().mul(100)

annee                  0.000000
patho_niv1             0.000000
patho_niv2            10.434783
patho_niv3            22.608696
top                    0.000000
cla_age_5              0.000000
sexe                   0.000000
region                 0.000000
dept                   0.000000
Ntop                  26.335162
Npop                   0.000000
prev                  26.335162
Niveau prioritaire     1.304348
libelle_classe_age     0.000000
libelle_sexe           0.000000
tri                    1.304348
dtype: float64

In [11]:
#Valeurs uniques par colonnes
colonnes = df_effectifs.columns.tolist()

df_effectifs[colonnes].nunique()

annee                    10
patho_niv1               18
patho_niv2               48
patho_niv3               61
top                      79
cla_age_5                21
sexe                      3
region                   19
dept                    102
Ntop                  30136
Npop                  16955
prev                  74942
Niveau prioritaire        5
libelle_classe_age       21
libelle_sexe              3
tri                      78
dtype: int64

In [35]:
#quelles sont des valeurs uniques dans la colonne "annee"
print(df_effectifs["annee"].unique())

#quelles sont des valeurs uniques dans la colonne "cla_age_5" et libelle_cla_age_5
print(df_effectifs["cla_age_5"].unique())
print(df_effectifs["libelle_classe_age"].unique())

#quelles sont les  valeurs uniques dans la colonne "sexe" et libelle_sexe
print(df_effectifs["sexe"].unique())
print(df_effectifs["libelle_sexe"].unique())

#quelles sont les  valeurs uniques dans la colonne "Niveau prioritaire"
print(df_effectifs["Niveau prioritaire"].unique())

[2020 2024 2018 2015 2016 2017 2019 2022 2023 2021]
<StringArray>
['50-54', '55-59', '60-64', '65-69', '70-74', '75-79', '80-84', '85-89',
 '90-94', '95et+', 'tsage', '00-04', '05-09', '10-14', '15-19', '20-24',
 '25-29', '30-34', '35-39', '40-44', '45-49']
Length: 21, dtype: str
<StringArray>
['de 50 à 54 ans', 'de 55 à 59 ans', 'de 60 à 64 ans', 'de 65 à 69 ans',
 'de 70 à 74 ans', 'de 75 à 79 ans', 'de 80 à 84 ans', 'de 85 à 89 ans',
 'de 90 à 94 ans', 'plus de 95 ans',      'tous âges',   'de 0 à 4 ans',
   'de 5 à 9 ans', 'de 10 à 14 ans', 'de 15 à 19 ans', 'de 20 à 24 ans',
 'de 25 à 29 ans', 'de 30 à 34 ans', 'de 35 à 39 ans', 'de 40 à 44 ans',
 'de 45 à 49 ans']
Length: 21, dtype: str
[2 9 1]
<StringArray>
['femmes', 'tous sexes', 'hommes']
Length: 3, dtype: str
<StringArray>
['2,3', '1,2,3', '3', '1', nan, '2']
Length: 6, dtype: str

In [51]:
#Quelles sont les valeurs uniques pour les pathologies de niveau 1
print(df_effectifs["patho_niv1"].unique())

<StringArray>
[                                                                                         'Maladies psychiatriques',
                                                           'Maladies respiratoires chroniques (hors mucoviscidose)',
                                                                'Maladies inflammatoires ou rares ou infection VIH',
                                                                                           'Maladies neurologiques',
 'Pas de pathologie repérée, traitement, maternité, hospitalisation ou traitement antalgique ou anti-inflammatoire',
                                                                                   'Total consommants tous régimes',
                                                                                                          'Cancers',
                                                                                                          'Diabète',
                                                              'Traitements du risque vasculaire (hors pathologies)',
                                                                             'Maternité (avec ou sans pathologies)',
                                                                                  'Maladies cardioneurovasculaires',
                                                             'Maladies du foie ou du pancréas (hors mucoviscidose)',
                  'Hospitalisations hors pathologies repérées (avec ou sans pathologies, traitements ou maternité)',
                                                                          'Insuffisance rénale chronique terminale',
                                                                      'Traitements psychotropes (hors pathologies)',
                                                                                    'Hospitalisation pour Covid-19',
    'Traitements antalgiques ou anti-inflammatoires (hors pathologies, traitements, maternité ou hospitalisations)',
                                                  'Affections de longue durée (dont 31 et 32) pour d'autres causes']
Length: 18, dtype: str

Je selectionne les categories suivantes qui peuvent etre liées à la maladies respiratoires (allergie, asthme, bronchiolite):
maladies respiratoires chroniques (hors mucoviscidose) 
hospitalisation pour Covid-19 (à partir de 2020) 
traitement antalgique ou anti-inflammatoire (hors pathologies, traitements, maternité ou hospitalisations) ;
hospitalisations hors pathologies repérées (avec ou sans pathologies, traitements ou maternité).

In [79]:
# 1. Définir les 4 catégories à explorer
categories = [
    "Maladies respiratoires chroniques (hors mucoviscidose)",
    "Hospitalisation pour Covid-19",
    "Traitements antalgiques ou anti-inflammatoires (hors pathologies, traitements, maternité ou hospitalisations)",
    "Hospitalisations hors pathologies repérées (avec ou sans pathologies, traitements ou maternité)"
]

# 2. Filtrer les données et garder les 3 niveaux
hierarchie = (
    df_effectifs.loc[
        df_effectifs["patho_niv1"].isin(categories),
        ["patho_niv1", "patho_niv2", "patho_niv3"]
    ]
    .drop_duplicates()
    .sort_values(["patho_niv1", "patho_niv2", "patho_niv3"])
    .reset_index(drop=True)
)

# 3. Afficher les sous-catégories pour chaque catégorie
for categorie, groupe in hierarchie.groupby("patho_niv1"):
    print(f"\nCATÉGORIE : {categorie}")
    display(groupe[["patho_niv2", "patho_niv3"]].reset_index(drop=True))

# 4. Résumer le nombre de valeurs différentes à chaque niveau
resume = hierarchie.groupby("patho_niv1").agg(
    nb_niv2=("patho_niv2", "nunique"),
    nb_niv3=("patho_niv3", "nunique")
)

display(resume)

CATÉGORIE : Hospitalisation pour Covid-19

                      patho_niv2                     patho_niv3
0  Hospitalisation pour Covid-19  Hospitalisation pour Covid-19

CATÉGORIE : Hospitalisations hors pathologies repérées (avec ou sans pathologies, traitements ou maternité)

,patho_niv2,patho_niv3
0,Hospitalisations hors pathologies repérées (av...,Hospitalisations hors pathologies repérées (av...

CATÉGORIE : Maladies respiratoires chroniques (hors mucoviscidose)

,patho_niv2,patho_niv3
0,Maladies respiratoires chroniques (hors mucovi...,Maladies respiratoires chroniques (hors mucovi...

CATÉGORIE : Traitements antalgiques ou anti-inflammatoires (hors pathologies, traitements, maternité ou hospitalisations)

,patho_niv2,patho_niv3
0,Traitements antalgiques ou anti-inflammatoires...,Traitements antalgiques ou anti-inflammatoires...

                                                    nb_niv2  nb_niv3
patho_niv1
Hospitalisation pour Covid-19                             1        1
Hospitalisations hors pathologies repérées (ave...        1        1
Maladies respiratoires chroniques (hors mucovis...        1        1
Traitements antalgiques ou anti-inflammatoires ...        1        1

In [ ]:
#Afficher le nombre de modalités de sexe, cla_age_5, dept et region  
display(df_effectifs["annee"].value_counts(dropna=False))
display(df_effectifs["sexe"].value_counts(dropna=False))
display(df_effectifs["cla_age_5"].value_counts(dropna=False))
display(df_effectifs["dept"].value_counts(dropna=False))
display(df_effectifs["region"].value_counts(dropna=False))

annee
2020    579600
2024    579600
2018    579600
2015    579600
2016    579600
2017    579600
2019    579600
2022    579600
2023    579600
2021    579600
Name: count, dtype: int64

sexe
9    1990800
2    1915200
1    1890000
Name: count, dtype: int64

cla_age_5
50-54    276000
55-59    276000
60-64    276000
65-69    276000
70-74    276000
75-79    276000
80-84    276000
85-89    276000
90-94    276000
95et+    276000
tsage    276000
00-04    276000
05-09    276000
10-14    276000
15-19    276000
20-24    276000
25-29    276000
30-34    276000
35-39    276000
40-44    276000
45-49    276000
Name: count, dtype: int64

dept
999    917700
971     48300
974     48300
77      48300
91      48300
        ...
52      48300
11      48300
07      48300
53      48300
04      48300
Name: count, Length: 102, dtype: int64

region
76    676200
75    627900
84    627900
44    531300
11    434700
27    434700
24    338100
93    338100
32    289800
52    289800
28    289800
53    241500
94    144900
1      96600
3      96600
4      96600
2      96600
6      96600
99     48300
Name: count, dtype: int64

In [27]:
# Statistics descriptives pour les colonnes numériques (Ntop, Npop et prev)
df_effectifs[["Ntop", "Npop", "prev"]].describe()

               Ntop          Npop          prev
count  4.269614e+06  5.796000e+06  4.269614e+06
mean   5.560028e+03  1.036321e+05  6.204748e+00
std    1.593980e+05  9.929227e+05  1.593149e+01
min    1.000000e+01  1.000000e+01  0.000000e+00
25%    5.000000e+01  7.740000e+03  2.740000e-01
50%    2.000000e+02  1.709000e+04  9.790000e-01
75%    9.500000e+02  4.285000e+04  4.198000e+00
max    6.882340e+07  6.882340e+07  1.000000e+02

Verification la coherence  des colonnes redondantes

In [ ]:
#vérifier si la prévalence publiée (prev) correspond au pourcentage calculé avec les effectifs du fichier.
# #Ntop : nombre de patients pris en charge pour la pathologie.
#Npop : population de référence.
#prev : prévalence publiée, exprimée en %.


# Sélectionner les lignes où la comparaison est possible
verif = (
    (df_effectifs["Npop"] > 0)
    & df_effectifs["Ntop"].notna()
    & df_effectifs["prev"].notna()
)

controle = df_effectifs.loc[
    verif, ["Ntop", "Npop", "prev"]
].copy()

# Recalculer le pourcentage
controle["prev_calculee"] = (
    100 * controle["Ntop"] / controle["Npop"]
)

# Mesurer la différence avec la valeur publiée
controle["ecart_absolu"] = (
    controle["prev"] - controle["prev_calculee"]
).abs()

controle["ecart_absolu"].describe()

count    4.269614e+06
mean     3.126424e-02
std      1.322324e-01
min      0.000000e+00
25%      2.320097e-03
50%      9.376384e-03
75%      2.580048e-02
max      3.478300e+01
Name: ecart_absolu, dtype: float64

Les écarts sont généralement faibles, qui peut apparaitre à cause des arrondis. Quelques écarts importants nécessitent un examen complémentaire

In [56]:
#le 10 plus grandes ecartes
controle.sort_values(
    "ecart_absolu", ascending=False
).head(10)

         Ntop  Npop    prev  prev_calculee  ecart_absolu
877489   20.0    20  65.217          100.0        34.783
877490   20.0    20  65.217          100.0        34.783
582863   10.0    20  81.250           50.0        31.250
2800316  10.0    20  81.250           50.0        31.250
4074949  10.0    20  77.778           50.0        27.778
5505036  10.0    20  77.778           50.0        27.778
5505035  10.0    20  77.778           50.0        27.778
4074948  10.0    20  77.778           50.0        27.778
934148   10.0    20  75.000           50.0        25.000
934149   10.0    20  75.000           50.0        25.000

Ntop = Npop ? cela signifierait que 100 % de la population de référence(Npop) de cette ligne est prise en charge pour la catégorie considérée. C'est quand mémé curieux. 
Comme la ligne corresponde à une combinaison (née, territoire, classe d’âge et sexe), pas la population entiere de departement, j'examine le contexte

In [ ]:
#J'examine le contexte
indices = controle.nlargest(10, "ecart_absolu").index

df_effectifs.loc[
    indices,
    ["annee", "top", "cla_age_5", "sexe",
     "region", "dept", "Ntop", "Npop", "prev"]
]

         annee          top cla_age_5  sexe  region dept  Ntop  Npop    prev
877489    2020  ALD_CAT_CAT     95et+     1       6  976  20.0    20  65.217
877490    2020  ALD_CAT_CAT     95et+     1       6  999  20.0    20  65.217
582863    2018  ALD_CAT_CAT     95et+     1       6  976  10.0    20  81.250
2800316   2018  ALD_CAT_CAT     95et+     1       6  999  10.0    20  81.250
4074948   2017  ALD_CAT_CAT     95et+     1       6  976  10.0    20  77.778
4074949   2017  ALD_CAT_CAT     95et+     1       6  999  10.0    20  77.778
5505035   2016  ALD_CAT_CAT     95et+     2       6  976  10.0    20  77.778
5505036   2016  ALD_CAT_CAT     95et+     2       6  999  10.0    20  77.778
934148    2019  ALD_CAT_CAT     95et+     1       6  976  10.0    20  75.000
934149    2019  ALD_CAT_CAT     95et+     1       6  999  10.0    20  75.000

les écarts les plus élevés concernent ici de très petits groupes de personnes âgées. Ils sont compatibles avec un effet d’arrondi des effectifs (si arrondis à la dizaine)

In [ ]:
#afficher les pathologies de niveau 1, 2 et 3 pour le top ALD_CAT_CAT
df_effectifs.loc[
    df_effectifs["top"] == "ALD_CAT_CAT",
    ["patho_niv1", "patho_niv2", "patho_niv3"]
].drop_duplicates()

,patho_niv1,patho_niv2,patho_niv3
489877,Affections de longue durée (dont 31 et 32) pou...,Affections de longue durée (dont 31 et 32) pou...,Affections de longue durée (dont 31 et 32) pou...

Visualisation des données

les maladies respiratoires chroniques, à l'échelle départementale, tous âges et sexes confondus, pour voir l'évolution annuelle de la prévalence.

In [84]:
for col in ["cla_age_5", "libelle_classe_age",
            "sexe", "libelle_sexe", "region", "dept"]:
    print(f"\n{col} :")
    print(df_effectifs[col].dropna().unique()[:30])

cla_age_5 :
<StringArray>
['50-54', '55-59', '60-64', '65-69', '70-74', '75-79', '80-84', '85-89',
 '90-94', '95et+', 'tsage', '00-04', '05-09', '10-14', '15-19', '20-24',
 '25-29', '30-34', '35-39', '40-44', '45-49']
Length: 21, dtype: str

libelle_classe_age :
<StringArray>
['de 50 à 54 ans', 'de 55 à 59 ans', 'de 60 à 64 ans', 'de 65 à 69 ans',
 'de 70 à 74 ans', 'de 75 à 79 ans', 'de 80 à 84 ans', 'de 85 à 89 ans',
 'de 90 à 94 ans', 'plus de 95 ans',      'tous âges',   'de 0 à 4 ans',
   'de 5 à 9 ans', 'de 10 à 14 ans', 'de 15 à 19 ans', 'de 20 à 24 ans',
 'de 25 à 29 ans', 'de 30 à 34 ans', 'de 35 à 39 ans', 'de 40 à 44 ans',
 'de 45 à 49 ans']
Length: 21, dtype: str

sexe :
[2 9 1]

libelle_sexe :
<StringArray>
['femmes', 'tous sexes', 'hommes']
Length: 3, dtype: str

region :
[ 1  3  4 11 24 27 32 44 52 53 75 76 84 93 94  2  6 28 99]

dept :
<StringArray>
['971', '999', '974',  '77',  '91',  '21',  '25',  '89',  '90',  '60',  '51',
  '57',  '67',  '08',  '44',  '49',  '22',  '35',  '16',  '79',  '86',  '87',
  '12',  '30',  '46',  '48',  '81',  '26',  '03',  '42']
Length: 30, dtype: str

In [83]:
resp = df_effectifs[
    df_effectifs["patho_niv1"] ==
    "Maladies respiratoires chroniques (hors mucoviscidose)"
]

display(
    resp[["annee", "top", "cla_age_5", "libelle_classe_age",
          "sexe", "libelle_sexe", "region", "dept",
          "Ntop", "Npop", "prev"]].head(10)
)

,annee,top,cla_age_5,libelle_classe_age,sexe,libelle_sexe,region,dept,Ntop,Npop,prev
1259,2020,RES_CAT_EXC,00-04,de 0 à 4 ans,1,hommes,2,972,470.0,8310,5.679
1260,2020,RES_CAT_EXC,00-04,de 0 à 4 ans,1,hommes,6,999,90.0,8130,1.046
1261,2020,RES_CAT_EXC,00-04,de 0 à 4 ans,1,hommes,11,92,3080.0,52210,5.899
1262,2020,RES_CAT_EXC,00-04,de 0 à 4 ans,1,hommes,11,95,2370.0,45900,5.168
1263,2020,RES_CAT_EXC,00-04,de 0 à 4 ans,1,hommes,11,999,21150.0,393510,5.373
1264,2020,RES_CAT_EXC,00-04,de 0 à 4 ans,1,hommes,24,28,660.0,11640,5.678
1265,2020,RES_CAT_EXC,00-04,de 0 à 4 ans,1,hommes,24,36,210.0,4300,4.908
1266,2020,RES_CAT_EXC,00-04,de 0 à 4 ans,1,hommes,24,45,860.0,18860,4.582
1267,2020,RES_CAT_EXC,00-04,de 0 à 4 ans,1,hommes,27,21,590.0,12790,4.591
1268,2020,RES_CAT_EXC,00-04,de 0 à 4 ans,1,hommes,27,999,2670.0,65780,4.056