Quelques modifications sur le fichier final pour harmoniser avec les autres fichiers avant le merge

In [13]:
import pandas as pd
import numpy as np

In [14]:
df_meteo_hebdo_clean_96 = pd.read_csv("../data/processed/df_meteo_hebdo_clean_96.csv")

df_meteo_hebdo_clean_96.info()

<class 'pandas.DataFrame'>
RangeIndex: 20160 entries, 0 to 20159
Data columns (total 27 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   annee_semaine                               20160 non-null  str
 1   code_dept                                   20160 non-null  str
 2   latitude                                    20160 non-null  float64
 3   longitude                                   20160 non-null  float64
 4   pression_mer                                20160 non-null  float64
 5   tendance_pression_3h                        20160 non-null  float64
 6   vent_direction                              20160 non-null  float64
 7   vent_vitesse                                20160 non-null  float64
 8   temperature_kelvin                          20160 non-null  float64
 9   humidite_relative                           20160 non-null  float64
 10  visibilite                                  20160 non-null  float64
 11  pression_station                            20160 non-null  float64
 12  periode_rafale                              20160 non-null  float64
 13  precipitation_1h                            20160 non-null  float64
 14  precipitation_3h                            20160 non-null  float64
 15  precipitation_6h                            20160 non-null  float64
 16  precipitation_12h                           20160 non-null  float64
 17  precipitation_24h                           20160 non-null  float64
 18  tp_averses_ou_orages                        20160 non-null  float64
 19  tp_brouillard                               20160 non-null  float64
 20  tp_brume_fumee_ou_phenomenes_particuliers   20160 non-null  float64
 21  tp_neige_precipitation_solide               20160 non-null  float64
 22  tp_phenomenes_recents_derniere_heure        20160 non-null  float64
 23  tp_pluie_ou_bruine                          20160 non-null  float64
 24  tp_sans_precipitation_visibilite_ou_nuages  20160 non-null  float64
 25  tp_tempete_poussiere_chasse_neige           20160 non-null  float64
 26  tp_temps_inconnu                            20160 non-null  float64
dtypes: float64(25), str(2)
memory usage: 4.2 MB

In [15]:
df_meteo_hebdo_clean_96.head(10)

,annee_semaine,code_dept,latitude,longitude,pression_mer,tendance_pression_3h,vent_direction,vent_vitesse,temperature_kelvin,humidite_relative,...,precipitation_24h,tp_averses_ou_orages,tp_brouillard,tp_brume_fumee_ou_phenomenes_particuliers,tp_neige_precipitation_solide,tp_phenomenes_recents_derniere_heure,tp_pluie_ou_bruine,tp_sans_precipitation_visibilite_ou_nuages,tp_tempete_poussiere_chasse_neige,tp_temps_inconnu
0,2020-W53,01,46.2056,5.2300,101025.833333,27.500000,320.833333,4.958333,274.637500,88.125000,...,124.5,0.0,0.0,0.0,1.0,3.0,3.0,17.0,0.0,0.0
1,2020-W53,02,49.5667,3.6167,101285.000000,34.583333,207.916667,1.125000,274.375000,93.541667,...,21.1,0.0,4.0,3.0,0.0,0.0,1.0,16.0,0.0,0.0
2,2020-W53,03,46.3333,3.1333,101203.333333,22.916667,222.500000,2.041667,273.545833,78.875000,...,14.2,0.0,0.0,1.0,0.0,0.0,0.0,23.0,0.0,0.0
3,2020-W53,04,44.0931,6.0856,101740.000000,-1.250000,139.583333,3.458333,273.425000,75.208333,...,18.5,0.0,0.0,0.0,2.0,0.0,0.0,22.0,0.0,0.0
4,2020-W53,05,44.5561,6.0719,101740.000000,-1.250000,139.583333,3.458333,273.425000,75.208333,...,18.5,0.0,0.0,0.0,2.0,0.0,0.0,22.0,0.0,0.0
5,2020-W53,06,43.7102,7.2620,100464.583333,-0.833333,164.166667,4.833333,280.754167,82.166667,...,500.5,3.0,0.0,0.0,0.0,3.0,14.0,4.0,0.0,0.0
6,2020-W53,07,44.7333,4.7500,100798.333333,17.500000,28.750000,5.791667,277.000000,76.208333,...,75.9,0.0,0.0,0.0,0.0,0.0,3.0,21.0,0.0,0.0
7,2020-W53,08,49.7500,4.7167,101285.000000,34.583333,207.916667,1.125000,274.375000,93.541667,...,21.1,0.0,4.0,3.0,0.0,0.0,1.0,16.0,0.0,0.0
8,2020-W53,09,42.9600,1.5300,101239.166667,12.916667,192.916667,1.416667,274.237500,84.791667,...,34.2,0.0,0.0,0.0,1.0,0.0,0.0,23.0,0.0,0.0
9,2020-W53,10,48.3000,4.0833,101297.916667,30.416667,306.666667,1.625000,273.662500,94.166667,...,6.8,0.0,1.0,14.0,1.0,0.0,1.0,7.0,0.0,0.0

In [16]:
#remplace le w en s pour les dates de la colonne annee_semaine
df_meteo_hebdo_clean_96['annee_semaine'] = df_meteo_hebdo_clean_96['annee_semaine'].str.replace('W', 'S', regex=False)

df_meteo_hebdo_clean_96.info()

df_meteo_hebdo_clean_96.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 20160 entries, 0 to 20159
Data columns (total 27 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   annee_semaine                               20160 non-null  str
 1   code_dept                                   20160 non-null  str
 2   latitude                                    20160 non-null  float64
 3   longitude                                   20160 non-null  float64
 4   pression_mer                                20160 non-null  float64
 5   tendance_pression_3h                        20160 non-null  float64
 6   vent_direction                              20160 non-null  float64
 7   vent_vitesse                                20160 non-null  float64
 8   temperature_kelvin                          20160 non-null  float64
 9   humidite_relative                           20160 non-null  float64
 10  visibilite                                  20160 non-null  float64
 11  pression_station                            20160 non-null  float64
 12  periode_rafale                              20160 non-null  float64
 13  precipitation_1h                            20160 non-null  float64
 14  precipitation_3h                            20160 non-null  float64
 15  precipitation_6h                            20160 non-null  float64
 16  precipitation_12h                           20160 non-null  float64
 17  precipitation_24h                           20160 non-null  float64
 18  tp_averses_ou_orages                        20160 non-null  float64
 19  tp_brouillard                               20160 non-null  float64
 20  tp_brume_fumee_ou_phenomenes_particuliers   20160 non-null  float64
 21  tp_neige_precipitation_solide               20160 non-null  float64
 22  tp_phenomenes_recents_derniere_heure        20160 non-null  float64
 23  tp_pluie_ou_bruine                          20160 non-null  float64
 24  tp_sans_precipitation_visibilite_ou_nuages  20160 non-null  float64
 25  tp_tempete_poussiere_chasse_neige           20160 non-null  float64
 26  tp_temps_inconnu                            20160 non-null  float64
dtypes: float64(25), str(2)
memory usage: 4.2 MB

,annee_semaine,code_dept,latitude,longitude,pression_mer,tendance_pression_3h,vent_direction,vent_vitesse,temperature_kelvin,humidite_relative,...,precipitation_24h,tp_averses_ou_orages,tp_brouillard,tp_brume_fumee_ou_phenomenes_particuliers,tp_neige_precipitation_solide,tp_phenomenes_recents_derniere_heure,tp_pluie_ou_bruine,tp_sans_precipitation_visibilite_ou_nuages,tp_tempete_poussiere_chasse_neige,tp_temps_inconnu
0,2020-S53,01,46.2056,5.2300,101025.833333,27.500000,320.833333,4.958333,274.637500,88.125000,...,124.5,0.0,0.0,0.0,1.0,3.0,3.0,17.0,0.0,0.0
1,2020-S53,02,49.5667,3.6167,101285.000000,34.583333,207.916667,1.125000,274.375000,93.541667,...,21.1,0.0,4.0,3.0,0.0,0.0,1.0,16.0,0.0,0.0
2,2020-S53,03,46.3333,3.1333,101203.333333,22.916667,222.500000,2.041667,273.545833,78.875000,...,14.2,0.0,0.0,1.0,0.0,0.0,0.0,23.0,0.0,0.0
3,2020-S53,04,44.0931,6.0856,101740.000000,-1.250000,139.583333,3.458333,273.425000,75.208333,...,18.5,0.0,0.0,0.0,2.0,0.0,0.0,22.0,0.0,0.0
4,2020-S53,05,44.5561,6.0719,101740.000000,-1.250000,139.583333,3.458333,273.425000,75.208333,...,18.5,0.0,0.0,0.0,2.0,0.0,0.0,22.0,0.0,0.0
5,2020-S53,06,43.7102,7.2620,100464.583333,-0.833333,164.166667,4.833333,280.754167,82.166667,...,500.5,3.0,0.0,0.0,0.0,3.0,14.0,4.0,0.0,0.0
6,2020-S53,07,44.7333,4.7500,100798.333333,17.500000,28.750000,5.791667,277.000000,76.208333,...,75.9,0.0,0.0,0.0,0.0,0.0,3.0,21.0,0.0,0.0
7,2020-S53,08,49.7500,4.7167,101285.000000,34.583333,207.916667,1.125000,274.375000,93.541667,...,21.1,0.0,4.0,3.0,0.0,0.0,1.0,16.0,0.0,0.0
8,2020-S53,09,42.9600,1.5300,101239.166667,12.916667,192.916667,1.416667,274.237500,84.791667,...,34.2,0.0,0.0,0.0,1.0,0.0,0.0,23.0,0.0,0.0
9,2020-S53,10,48.3000,4.0833,101297.916667,30.416667,306.666667,1.625000,273.662500,94.166667,...,6.8,0.0,1.0,14.0,1.0,0.0,1.0,7.0,0.0,0.0

In [17]:
#retire les colonnes latitude et longitude car plus utilisées
df_meteo_hebdo_clean_96 = df_meteo_hebdo_clean_96.drop(columns=['latitude', 'longitude'], errors='ignore')

df_meteo_hebdo_clean_96.info()

df_meteo_hebdo_clean_96.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 20160 entries, 0 to 20159
Data columns (total 25 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   annee_semaine                               20160 non-null  str
 1   code_dept                                   20160 non-null  str
 2   pression_mer                                20160 non-null  float64
 3   tendance_pression_3h                        20160 non-null  float64
 4   vent_direction                              20160 non-null  float64
 5   vent_vitesse                                20160 non-null  float64
 6   temperature_kelvin                          20160 non-null  float64
 7   humidite_relative                           20160 non-null  float64
 8   visibilite                                  20160 non-null  float64
 9   pression_station                            20160 non-null  float64
 10  periode_rafale                              20160 non-null  float64
 11  precipitation_1h                            20160 non-null  float64
 12  precipitation_3h                            20160 non-null  float64
 13  precipitation_6h                            20160 non-null  float64
 14  precipitation_12h                           20160 non-null  float64
 15  precipitation_24h                           20160 non-null  float64
 16  tp_averses_ou_orages                        20160 non-null  float64
 17  tp_brouillard                               20160 non-null  float64
 18  tp_brume_fumee_ou_phenomenes_particuliers   20160 non-null  float64
 19  tp_neige_precipitation_solide               20160 non-null  float64
 20  tp_phenomenes_recents_derniere_heure        20160 non-null  float64
 21  tp_pluie_ou_bruine                          20160 non-null  float64
 22  tp_sans_precipitation_visibilite_ou_nuages  20160 non-null  float64
 23  tp_tempete_poussiere_chasse_neige           20160 non-null  float64
 24  tp_temps_inconnu                            20160 non-null  float64
dtypes: float64(23), str(2)
memory usage: 3.8 MB

,annee_semaine,code_dept,pression_mer,tendance_pression_3h,vent_direction,vent_vitesse,temperature_kelvin,humidite_relative,visibilite,pression_station,...,precipitation_24h,tp_averses_ou_orages,tp_brouillard,tp_brume_fumee_ou_phenomenes_particuliers,tp_neige_precipitation_solide,tp_phenomenes_recents_derniere_heure,tp_pluie_ou_bruine,tp_sans_precipitation_visibilite_ou_nuages,tp_tempete_poussiere_chasse_neige,tp_temps_inconnu
0,2020-S53,01,101025.833333,27.500000,320.833333,4.958333,274.637500,88.125000,12933.750000,98070.833333,...,124.5,0.0,0.0,0.0,1.0,3.0,3.0,17.0,0.0,0.0
1,2020-S53,02,101285.000000,34.583333,207.916667,1.125000,274.375000,93.541667,6009.166667,100099.166667,...,21.1,0.0,4.0,3.0,0.0,0.0,1.0,16.0,0.0,0.0
2,2020-S53,03,101203.333333,22.916667,222.500000,2.041667,273.545833,78.875000,21840.416667,97190.416667,...,14.2,0.0,0.0,1.0,0.0,0.0,0.0,23.0,0.0,0.0
3,2020-S53,04,101740.000000,-1.250000,139.583333,3.458333,273.425000,75.208333,17287.916667,90337.500000,...,18.5,0.0,0.0,0.0,2.0,0.0,0.0,22.0,0.0,0.0
4,2020-S53,05,101740.000000,-1.250000,139.583333,3.458333,273.425000,75.208333,17287.916667,90337.500000,...,18.5,0.0,0.0,0.0,2.0,0.0,0.0,22.0,0.0,0.0
5,2020-S53,06,100464.583333,-0.833333,164.166667,4.833333,280.754167,82.166667,21674.583333,100148.333333,...,500.5,3.0,0.0,0.0,0.0,3.0,14.0,4.0,0.0,0.0
6,2020-S53,07,100798.333333,17.500000,28.750000,5.791667,277.000000,76.208333,19222.916667,99885.833333,...,75.9,0.0,0.0,0.0,0.0,0.0,3.0,21.0,0.0,0.0
7,2020-S53,08,101285.000000,34.583333,207.916667,1.125000,274.375000,93.541667,6009.166667,100099.166667,...,21.1,0.0,4.0,3.0,0.0,0.0,1.0,16.0,0.0,0.0
8,2020-S53,09,101239.166667,12.916667,192.916667,1.416667,274.237500,84.791667,18460.833333,96176.666667,...,34.2,0.0,0.0,0.0,1.0,0.0,0.0,23.0,0.0,0.0
9,2020-S53,10,101297.916667,30.416667,306.666667,1.625000,273.662500,94.166667,4897.500000,99821.250000,...,6.8,0.0,1.0,14.0,1.0,0.0,1.0,7.0,0.0,0.0

In [18]:
#rename the 'annee_semaine' column to 'date_semaine'
df_meteo_hebdo_clean_96 = df_meteo_hebdo_clean_96.rename(columns={'annee_semaine': 'date_semaine'})

df_meteo_hebdo_clean_96.info()

df_meteo_hebdo_clean_96.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 20160 entries, 0 to 20159
Data columns (total 25 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   date_semaine                                20160 non-null  str
 1   code_dept                                   20160 non-null  str
 2   pression_mer                                20160 non-null  float64
 3   tendance_pression_3h                        20160 non-null  float64
 4   vent_direction                              20160 non-null  float64
 5   vent_vitesse                                20160 non-null  float64
 6   temperature_kelvin                          20160 non-null  float64
 7   humidite_relative                           20160 non-null  float64
 8   visibilite                                  20160 non-null  float64
 9   pression_station                            20160 non-null  float64
 10  periode_rafale                              20160 non-null  float64
 11  precipitation_1h                            20160 non-null  float64
 12  precipitation_3h                            20160 non-null  float64
 13  precipitation_6h                            20160 non-null  float64
 14  precipitation_12h                           20160 non-null  float64
 15  precipitation_24h                           20160 non-null  float64
 16  tp_averses_ou_orages                        20160 non-null  float64
 17  tp_brouillard                               20160 non-null  float64
 18  tp_brume_fumee_ou_phenomenes_particuliers   20160 non-null  float64
 19  tp_neige_precipitation_solide               20160 non-null  float64
 20  tp_phenomenes_recents_derniere_heure        20160 non-null  float64
 21  tp_pluie_ou_bruine                          20160 non-null  float64
 22  tp_sans_precipitation_visibilite_ou_nuages  20160 non-null  float64
 23  tp_tempete_poussiere_chasse_neige           20160 non-null  float64
 24  tp_temps_inconnu                            20160 non-null  float64
dtypes: float64(23), str(2)
memory usage: 3.8 MB

,date_semaine,code_dept,pression_mer,tendance_pression_3h,vent_direction,vent_vitesse,temperature_kelvin,humidite_relative,visibilite,pression_station,...,precipitation_24h,tp_averses_ou_orages,tp_brouillard,tp_brume_fumee_ou_phenomenes_particuliers,tp_neige_precipitation_solide,tp_phenomenes_recents_derniere_heure,tp_pluie_ou_bruine,tp_sans_precipitation_visibilite_ou_nuages,tp_tempete_poussiere_chasse_neige,tp_temps_inconnu
0,2020-S53,01,101025.833333,27.500000,320.833333,4.958333,274.637500,88.125000,12933.750000,98070.833333,...,124.5,0.0,0.0,0.0,1.0,3.0,3.0,17.0,0.0,0.0
1,2020-S53,02,101285.000000,34.583333,207.916667,1.125000,274.375000,93.541667,6009.166667,100099.166667,...,21.1,0.0,4.0,3.0,0.0,0.0,1.0,16.0,0.0,0.0
2,2020-S53,03,101203.333333,22.916667,222.500000,2.041667,273.545833,78.875000,21840.416667,97190.416667,...,14.2,0.0,0.0,1.0,0.0,0.0,0.0,23.0,0.0,0.0
3,2020-S53,04,101740.000000,-1.250000,139.583333,3.458333,273.425000,75.208333,17287.916667,90337.500000,...,18.5,0.0,0.0,0.0,2.0,0.0,0.0,22.0,0.0,0.0
4,2020-S53,05,101740.000000,-1.250000,139.583333,3.458333,273.425000,75.208333,17287.916667,90337.500000,...,18.5,0.0,0.0,0.0,2.0,0.0,0.0,22.0,0.0,0.0
5,2020-S53,06,100464.583333,-0.833333,164.166667,4.833333,280.754167,82.166667,21674.583333,100148.333333,...,500.5,3.0,0.0,0.0,0.0,3.0,14.0,4.0,0.0,0.0
6,2020-S53,07,100798.333333,17.500000,28.750000,5.791667,277.000000,76.208333,19222.916667,99885.833333,...,75.9,0.0,0.0,0.0,0.0,0.0,3.0,21.0,0.0,0.0
7,2020-S53,08,101285.000000,34.583333,207.916667,1.125000,274.375000,93.541667,6009.166667,100099.166667,...,21.1,0.0,4.0,3.0,0.0,0.0,1.0,16.0,0.0,0.0
8,2020-S53,09,101239.166667,12.916667,192.916667,1.416667,274.237500,84.791667,18460.833333,96176.666667,...,34.2,0.0,0.0,0.0,1.0,0.0,0.0,23.0,0.0,0.0
9,2020-S53,10,101297.916667,30.416667,306.666667,1.625000,273.662500,94.166667,4897.500000,99821.250000,...,6.8,0.0,1.0,14.0,1.0,0.0,1.0,7.0,0.0,0.0

In [19]:
# Conserver uniquement les lignes qui ne contiennent pas '2020-S53' ni '2025-S01'
# Identifier les index des lignes à supprimer
index_to_drop = df_meteo_hebdo_clean_96[df_meteo_hebdo_clean_96['date_semaine'].isin(['2020-S53', '2025-S01'])].index

# Supprimer ces lignes du DataFrame
df_meteo_hebdo_clean_96 = df_meteo_hebdo_clean_96.drop(index=index_to_drop)

df_meteo_hebdo_clean_96.info()

df_meteo_hebdo_clean_96.head(10)

display(df_meteo_hebdo_clean_96['date_semaine'].unique())

<class 'pandas.DataFrame'>
Index: 19968 entries, 96 to 20063
Data columns (total 25 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   date_semaine                                19968 non-null  str
 1   code_dept                                   19968 non-null  str
 2   pression_mer                                19968 non-null  float64
 3   tendance_pression_3h                        19968 non-null  float64
 4   vent_direction                              19968 non-null  float64
 5   vent_vitesse                                19968 non-null  float64
 6   temperature_kelvin                          19968 non-null  float64
 7   humidite_relative                           19968 non-null  float64
 8   visibilite                                  19968 non-null  float64
 9   pression_station                            19968 non-null  float64
 10  periode_rafale                              19968 non-null  float64
 11  precipitation_1h                            19968 non-null  float64
 12  precipitation_3h                            19968 non-null  float64
 13  precipitation_6h                            19968 non-null  float64
 14  precipitation_12h                           19968 non-null  float64
 15  precipitation_24h                           19968 non-null  float64
 16  tp_averses_ou_orages                        19968 non-null  float64
 17  tp_brouillard                               19968 non-null  float64
 18  tp_brume_fumee_ou_phenomenes_particuliers   19968 non-null  float64
 19  tp_neige_precipitation_solide               19968 non-null  float64
 20  tp_phenomenes_recents_derniere_heure        19968 non-null  float64
 21  tp_pluie_ou_bruine                          19968 non-null  float64
 22  tp_sans_precipitation_visibilite_ou_nuages  19968 non-null  float64
 23  tp_tempete_poussiere_chasse_neige           19968 non-null  float64
 24  tp_temps_inconnu                            19968 non-null  float64
dtypes: float64(23), str(2)
memory usage: 4.0 MB

<StringArray>
['2021-S01', '2021-S02', '2021-S03', '2021-S04', '2021-S05', '2021-S06',
 '2021-S07', '2021-S08', '2021-S09', '2021-S10',
 ...
 '2024-S43', '2024-S44', '2024-S45', '2024-S46', '2024-S47', '2024-S48',
 '2024-S49', '2024-S50', '2024-S51', '2024-S52']
Length: 208, dtype: str

In [20]:
#exporte le dataframe final_meteo_hebdo_clean_96 en csv
df_meteo_hebdo_clean_96.to_csv("../data/final_metropole/final_meteo_hebdo_clean_96.csv", index=False, encoding='utf-8')

In [21]:
#vérifie que le fichier final_meteo_hebdo_clean_96.csv a bien été créé et qu'il contient les bonnes colonnes
final_meteo_hebdo_clean_96 = pd.read_csv("../data/final_metropole/final_meteo_hebdo_clean_96.csv")

final_meteo_hebdo_clean_96.info()

final_meteo_hebdo_clean_96.head(10)

final_meteo_hebdo_clean_96['date_semaine'].unique()

<class 'pandas.DataFrame'>
RangeIndex: 19968 entries, 0 to 19967
Data columns (total 25 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   date_semaine                                19968 non-null  str
 1   code_dept                                   19968 non-null  str
 2   pression_mer                                19968 non-null  float64
 3   tendance_pression_3h                        19968 non-null  float64
 4   vent_direction                              19968 non-null  float64
 5   vent_vitesse                                19968 non-null  float64
 6   temperature_kelvin                          19968 non-null  float64
 7   humidite_relative                           19968 non-null  float64
 8   visibilite                                  19968 non-null  float64
 9   pression_station                            19968 non-null  float64
 10  periode_rafale                              19968 non-null  float64
 11  precipitation_1h                            19968 non-null  float64
 12  precipitation_3h                            19968 non-null  float64
 13  precipitation_6h                            19968 non-null  float64
 14  precipitation_12h                           19968 non-null  float64
 15  precipitation_24h                           19968 non-null  float64
 16  tp_averses_ou_orages                        19968 non-null  float64
 17  tp_brouillard                               19968 non-null  float64
 18  tp_brume_fumee_ou_phenomenes_particuliers   19968 non-null  float64
 19  tp_neige_precipitation_solide               19968 non-null  float64
 20  tp_phenomenes_recents_derniere_heure        19968 non-null  float64
 21  tp_pluie_ou_bruine                          19968 non-null  float64
 22  tp_sans_precipitation_visibilite_ou_nuages  19968 non-null  float64
 23  tp_tempete_poussiere_chasse_neige           19968 non-null  float64
 24  tp_temps_inconnu                            19968 non-null  float64
dtypes: float64(23), str(2)
memory usage: 3.8 MB

<StringArray>
['2021-S01', '2021-S02', '2021-S03', '2021-S04', '2021-S05', '2021-S06',
 '2021-S07', '2021-S08', '2021-S09', '2021-S10',
 ...
 '2024-S43', '2024-S44', '2024-S45', '2024-S46', '2024-S47', '2024-S48',
 '2024-S49', '2024-S50', '2024-S51', '2024-S52']
Length: 208, dtype: str