Probleme incohérence sur les precipitations 
trouver d'où cela vient

In [2]:
import pandas as pd
import numpy as np

Merge_final = pd.read_csv("../data/final_metropole/Merge_final.csv")

Merge_final.info()

Merge_final.head()

<class 'pandas.DataFrame'>
RangeIndex: 19968 entries, 0 to 19967
Data columns (total 76 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   date_semaine                                19968 non-null  str
 1   code_dept                                   19968 non-null  object
 2   As in PM10                                  19968 non-null  float64
 3   BaP in PM10                                 19968 non-null  float64
 4   Cd in PM10                                  19968 non-null  float64
 5   Ni in PM10                                  19968 non-null  float64
 6   Pb in PM10                                  19968 non-null  float64
 7   pression_mer                                19968 non-null  float64
 8   tendance_pression_3h                        19968 non-null  float64
 9   vent_direction                              19968 non-null  float64
 10  vent_vitesse                                19968 non-null  float64
 11  temperature_kelvin                          19968 non-null  float64
 12  humidite_relative                           19968 non-null  float64
 13  visibilite                                  19968 non-null  float64
 14  pression_station                            19968 non-null  float64
 15  periode_rafale                              19968 non-null  float64
 16  precipitation_1h                            19968 non-null  float64
 17  precipitation_3h                            19968 non-null  float64
 18  precipitation_6h                            19968 non-null  float64
 19  precipitation_12h                           19968 non-null  float64
 20  precipitation_24h                           19968 non-null  float64
 21  tp_averses_ou_orages                        19968 non-null  float64
 22  tp_brouillard                               19968 non-null  float64
 23  tp_brume_fumee_ou_phenomenes_particuliers   19968 non-null  float64
 24  tp_neige_precipitation_solide               19968 non-null  float64
 25  tp_phenomenes_recents_derniere_heure        19968 non-null  float64
 26  tp_pluie_ou_bruine                          19968 non-null  float64
 27  tp_sans_precipitation_visibilite_ou_nuages  19968 non-null  float64
 28  tp_tempete_poussiere_chasse_neige           19968 non-null  float64
 29  tp_temps_inconnu                            19968 non-null  float64
 30  TousAge_allergie_urgences                   19968 non-null  float64
 31  65plus_allergie_urgences                    19968 non-null  float64
 32  0_14_allergie_urgences                      19968 non-null  float64
 33  15_64_allergie_urgences                     19968 non-null  float64
 34  0_14_asthme_urgences                        19968 non-null  float64
 35  15_64_asthme_urgences                       19968 non-null  float64
 36  TousAge_asthme_urgences                     19968 non-null  float64
 37  65plus_asthme_urgences                      19968 non-null  float64
 38  0an_bronchiolite_urgences                   19908 non-null  float64
 39  TousAge_allergie_hospitalisation            19892 non-null  float64
 40  65plus_allergie_hospitalisation             19862 non-null  float64
 41  0_14_allergie_hospitalisation               19714 non-null  float64
 42  15_64_allergie_hospitalisation              19850 non-null  float64
 43  0_14_asthme_hospitalisation                 19714 non-null  float64
 44  15_64_asthme_hospitalisation                19850 non-null  float64
 45  TousAge_asthme_hospitalisation              19892 non-null  float64
 46  65plus_asthme_hospitalisation               19862 non-null  float64
 47  0an_bronchiolite_hospitalisation            18633 non-null  float64
 48  Ntop_Maladie_Respi_Chronique_tsage_9        19968 non-null  float64
 49  Npop_Maladie_Respi_Chronique_tsage_9        19968 non-null  float64
 50  prev_Maladie_Respi_Chronique_tsage_9        19968 non-null  float64
 51  Ntop_Maladie_Respi_Chronique_0-14_9         19968 non-null  float64
 52  Ntop_Maladie_Respi_Chronique_15-64_9        19968 non-null  float64
 53  Ntop_Maladie_Respi_Chronique_65+_9          19968 non-null  float64
 54  Npop_Maladie_Respi_Chronique_0-14_9         19968 non-null  float64
 55  Npop_Maladie_Respi_Chronique_15-64_9        19968 non-null  float64
 56  Npop_Maladie_Respi_Chronique_65+_9          19968 non-null  float64
 57  prev_calc_Maladie_Respi_Chronique_0-14_9    19968 non-null  float64
 58  prev_calc_Maladie_Respi_Chronique_15-64_9   19968 non-null  float64
 59  prev_calc_Maladie_Respi_Chronique_65+_9     19968 non-null  float64
 60  nom_dep                                     19968 non-null  str
 61  pct_urbain                                  19968 non-null  float64
 62  pct_artisans                                19968 non-null  float64
 63  pct_cadres                                  19968 non-null  float64
 64  pct_prof_inter                              19968 non-null  float64
 65  pct_employes                                19968 non-null  float64
 66  pct_ouvriers                                19968 non-null  float64
 67  pct_retraites                               19968 non-null  float64
 68  pct_sans_activite                           19968 non-null  float64
 69  pct_agriculteurs                            19968 non-null  float64
 70  densite_generalistes                        19968 non-null  float64
 71  densite_pediatres                           19968 non-null  float64
 72  densite_pneumologues                        19968 non-null  float64
 73  densite_allergologues                       19968 non-null  float64
 74  densite_kines                               19968 non-null  float64
 75  sos_present                                 19968 non-null  bool
dtypes: bool(1), float64(72), object(1), str(2)
memory usage: 11.4+ MB

C:\Users\gauxm\AppData\Local\Temp\ipykernel_12896\4033532219.py:4: DtypeWarning: Columns (1: code_dept) have mixed types. Specify dtype option on import or set low_memory=False.
  Merge_final = pd.read_csv("../data/final_metropole/Merge_final.csv")

,date_semaine,code_dept,As in PM10,BaP in PM10,Cd in PM10,Ni in PM10,Pb in PM10,pression_mer,tendance_pression_3h,vent_direction,...,pct_ouvriers,pct_retraites,pct_sans_activite,pct_agriculteurs,densite_generalistes,densite_pediatres,densite_pneumologues,densite_allergologues,densite_kines,sos_present
0,2021-S01,01,0.326250,0.610000,0.0500,0.4225,0.002025,101586.607143,13.928571,258.750000,...,14.2,26.0,12.9,0.6,53.439748,6.878368,1.016517,0.290433,77.400505,False
1,2021-S02,01,0.491563,1.065833,0.1375,3.0825,0.005350,102439.285714,14.285714,191.071429,...,14.2,26.0,12.9,0.6,53.439748,6.878368,1.016517,0.290433,77.400505,False
2,2021-S03,01,0.581875,0.396667,0.0800,5.8525,0.008425,101053.392857,-43.392857,170.178571,...,14.2,26.0,12.9,0.6,53.439748,6.878368,1.016517,0.290433,77.400505,False
3,2021-S04,01,0.399687,0.385833,0.0900,3.4125,0.006250,101230.000000,-12.500000,193.750000,...,14.2,26.0,12.9,0.6,53.439748,6.878368,1.016517,0.290433,77.400505,False
4,2021-S05,01,0.390000,0.360833,0.0850,1.2350,0.004900,100684.107143,6.250000,162.857143,...,14.2,26.0,12.9,0.6,53.439748,6.878368,1.016517,0.290433,77.400505,False

In [3]:
import pandas as pd
import plotly.express as px

# Supposons que ton DataFrame source s'appelle df et contienne tes colonnes de précipitations
# Si tes données sont au format large (une colonne par variable), on les passe au format long :
cols_precip = [
    'precipitation_1h', 
    'precipitation_3h', 
    'precipitation_6h', 
    'precipitation_12h', 
    'precipitation_24h'
]

df_long = Merge_final.melt(
    value_vars=cols_precip, 
    var_name='Variables de précipitation', 
    value_name='Cumul hebdomadaire (mm)'
)

# Création du boxplot interactif avec Plotly Express
fig = px.box(
    df_long,
    x='Cumul hebdomadaire (mm)',
    y='Variables de précipitation',
    orientation='h',
    color='Variables de précipitation',
    title='Distribution des cumuls hebdomadaires de précipitations',
    template='plotly_white'
)

# Personnalisation de l'affichage
fig.update_layout(
    xaxis_title='Cumul hebdomadaire (mm)',
    yaxis_title='Variables de précipitation',
    showlegend=False
)

# Affichage du graphique interactif (dans un Jupyter Notebook ou export HTML)
fig.show()

# Optionnel : pour l'exporter en fichier HTML interactif
# fig.write_html("boxplot_interactif.html")

In [4]:
import pandas as pd

# 1. Sélection des colonnes et création d'une copie de travail
df_ratio = Merge_final[['date_semaine', 'code_dept', 'precipitation_1h', 'precipitation_3h', 'precipitation_6h', 'precipitation_12h', 'precipitation_24h']].copy()

# 2. Ajout de la colonne du ratio (24h / 3h) en évitant la division par zéro
df_ratio['ratio_24h_3h'] = df_ratio['precipitation_24h'] / df_ratio['precipitation_3h'].replace(0, pd.NA)

# 3. Affichage des 20 premières lignes
df_ratio.head(20)

,date_semaine,code_dept,precipitation_1h,precipitation_3h,precipitation_6h,precipitation_12h,precipitation_24h,ratio_24h_3h
0,2021-S01,01,-0.4,-0.6,-1.0,-1.9,-3.4,5.666667
1,2021-S02,01,12.8,44.5,89.7,179.5,347.9,7.817978
2,2021-S03,01,4.6,18.0,36.9,75.7,164.5,9.138889
3,2021-S04,01,9.8,22.1,45.8,93.6,190.3,8.61086
4,2021-S05,01,13.1,26.9,54.3,109.4,211.2,7.851301
5,2021-S06,01,3.6,8.5,17.5,34.3,73.1,8.6
6,2021-S07,01,-0.1,-0.2,-0.3,-0.5,-0.9,4.5
7,2021-S08,01,0.1,-0.2,-0.1,0.1,0.5,-2.5
8,2021-S09,01,-0.3,-0.4,-0.6,-0.8,-1.2,3.0
9,2021-S10,01,2.4,14.1,29.0,58.1,113.2,8.028369
10,2021-S11,01,5.1,18.7,38.2,77.3,158.2,8.459893
11,2021-S12,01,0.3,5.1,10.4,20.8,41.6,8.156863
12,2021-S13,01,0.0,0.0,0.0,0.0,0.0,<NA>
13,2021-S14,01,5.5,14.9,23.2,23.2,23.2,1.557047
14,2021-S15,01,1.3,7.5,21.7,66.9,157.6,21.013333
15,2021-S16,01,0.1,2.2,3.9,9.4,20.5,9.318182
16,2021-S17,01,11.0,33.7,68.2,137.5,274.4,8.142433
17,2021-S18,01,3.9,13.6,27.6,55.6,114.0,8.382353
18,2021-S19,01,38.9,128.3,257.6,510.7,1002.5,7.813718
19,2021-S20,01,5.4,20.3,41.2,89.0,199.1,9.807882

Sur les précipitations, une piste pour trancher : si la 24h est renseignée à chaque relevé de 3h, chaque épisode de pluie apparaît dans 8 relevés de suite, et la somme hebdo le compte 8 fois. Divisez la somme hebdo de la 24h par celle de la 3h, si vous tombez vers 8 vous avez la réponse. Regardez aussi combien de stations vous avez par département. Garder la 3h sommée me paraît le bon choix.

Je suis reparti sur les raw data pour revoir à quoi ça ressemble: les mesures sont donc bien faite toute les 3h et à chaque fois effectivement les mesures des précipitations sont prises. Il y a donc bien un effet cumulatif ( si on fait la somme de tout les 3h on obtient le 24h)
J'ai donc fait une grosse erreur quand j'ai agréger par semaine en faisant la somme seul.
Les mesures étant faite toute les 3 heures seul les 3h sommée sur les précipitation_3h est valable ici => la seule à garder du coup ?
J'ai aussi vérifié sur une partie des données du merge final effectivement c'est ça
Vraiment désolé pour cette grossière erreur que j'ai faite

On va donc garder que 3h

De plus les données de periode rafale est une métadonnée de mesure on va donc la retirer également

In [7]:
df_meteo = pd.read_csv("../data/final_metropole/final_meteo_hebdo_clean_96.csv")

df_meteo.info()

df_meteo.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 19968 entries, 0 to 19967
Data columns (total 25 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   date_semaine                                19968 non-null  str
 1   code_dept                                   19968 non-null  str
 2   pression_mer                                19968 non-null  float64
 3   tendance_pression_3h                        19968 non-null  float64
 4   vent_direction                              19968 non-null  float64
 5   vent_vitesse                                19968 non-null  float64
 6   temperature_kelvin                          19968 non-null  float64
 7   humidite_relative                           19968 non-null  float64
 8   visibilite                                  19968 non-null  float64
 9   pression_station                            19968 non-null  float64
 10  periode_rafale                              19968 non-null  float64
 11  precipitation_1h                            19968 non-null  float64
 12  precipitation_3h                            19968 non-null  float64
 13  precipitation_6h                            19968 non-null  float64
 14  precipitation_12h                           19968 non-null  float64
 15  precipitation_24h                           19968 non-null  float64
 16  tp_averses_ou_orages                        19968 non-null  float64
 17  tp_brouillard                               19968 non-null  float64
 18  tp_brume_fumee_ou_phenomenes_particuliers   19968 non-null  float64
 19  tp_neige_precipitation_solide               19968 non-null  float64
 20  tp_phenomenes_recents_derniere_heure        19968 non-null  float64
 21  tp_pluie_ou_bruine                          19968 non-null  float64
 22  tp_sans_precipitation_visibilite_ou_nuages  19968 non-null  float64
 23  tp_tempete_poussiere_chasse_neige           19968 non-null  float64
 24  tp_temps_inconnu                            19968 non-null  float64
dtypes: float64(23), str(2)
memory usage: 3.8 MB

,date_semaine,code_dept,pression_mer,tendance_pression_3h,vent_direction,vent_vitesse,temperature_kelvin,humidite_relative,visibilite,pression_station,...,precipitation_24h,tp_averses_ou_orages,tp_brouillard,tp_brume_fumee_ou_phenomenes_particuliers,tp_neige_precipitation_solide,tp_phenomenes_recents_derniere_heure,tp_pluie_ou_bruine,tp_sans_precipitation_visibilite_ou_nuages,tp_tempete_poussiere_chasse_neige,tp_temps_inconnu
0,2021-S01,01,101586.607143,13.928571,258.750000,1.875000,272.803571,87.767857,9165.000000,98595.535714,...,-3.4,0.0,0.0,6.0,0.0,3.0,1.0,46.0,0.0,0.0
1,2021-S01,02,101806.250000,19.464286,163.035714,2.142857,274.617857,88.946429,11832.142857,100615.357143,...,-3.1,0.0,2.0,4.0,0.0,0.0,4.0,46.0,0.0,0.0
2,2021-S01,03,101656.428571,16.250000,206.071429,1.339286,272.644643,82.392857,11617.857143,97613.035714,...,13.3,0.0,1.0,10.0,2.0,0.0,0.0,43.0,0.0,0.0
3,2021-S01,04,101740.000000,11.071429,106.071429,3.214286,271.585714,59.089286,18886.250000,90856.785714,...,5.5,0.0,0.0,0.0,3.0,0.0,0.0,53.0,0.0,0.0
4,2021-S01,05,101740.000000,11.071429,106.071429,3.214286,271.585714,59.089286,18886.250000,90856.785714,...,5.5,0.0,0.0,0.0,3.0,0.0,0.0,53.0,0.0,0.0
5,2021-S01,06,101048.571429,10.000000,280.892857,3.892857,279.242857,67.125000,41569.464286,100728.750000,...,69.8,1.0,0.0,1.0,0.0,5.0,0.0,49.0,0.0,0.0
6,2021-S01,07,101403.214286,12.500000,72.678571,4.660714,275.457143,72.107143,18030.714286,100479.285714,...,23.6,0.0,0.0,0.0,2.0,0.0,1.0,53.0,0.0,0.0
7,2021-S01,08,101806.250000,19.464286,163.035714,2.142857,274.617857,88.946429,11832.142857,100615.357143,...,-3.1,0.0,2.0,4.0,0.0,0.0,4.0,46.0,0.0,0.0
8,2021-S01,09,101551.428571,16.607143,70.535714,0.446429,272.439286,88.696429,12063.392857,96440.000000,...,130.6,0.0,1.0,3.0,11.0,0.0,0.0,41.0,0.0,0.0
9,2021-S01,10,101781.428571,19.107143,186.607143,1.571429,274.235714,88.607143,9799.464286,100302.500000,...,32.5,0.0,1.0,17.0,0.0,0.0,8.0,30.0,0.0,0.0

In [9]:
#supprimer les colonnes 
# Liste propre des colonnes à supprimer (en vérifiant les espaces)
cols_a_supprimer = [
    'precipitation_24h', 
    'precipitation_12h', 
    'precipitation_1h', 
    'precipitation_6h', 
    'periode_rafale'
]

# Suppression et affichage
df_meteo = df_meteo.drop(columns=cols_a_supprimer)

df_meteo.info()
display(df_meteo.head(10))

<class 'pandas.DataFrame'>
RangeIndex: 19968 entries, 0 to 19967
Data columns (total 20 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   date_semaine                                19968 non-null  str
 1   code_dept                                   19968 non-null  str
 2   pression_mer                                19968 non-null  float64
 3   tendance_pression_3h                        19968 non-null  float64
 4   vent_direction                              19968 non-null  float64
 5   vent_vitesse                                19968 non-null  float64
 6   temperature_kelvin                          19968 non-null  float64
 7   humidite_relative                           19968 non-null  float64
 8   visibilite                                  19968 non-null  float64
 9   pression_station                            19968 non-null  float64
 10  precipitation_3h                            19968 non-null  float64
 11  tp_averses_ou_orages                        19968 non-null  float64
 12  tp_brouillard                               19968 non-null  float64
 13  tp_brume_fumee_ou_phenomenes_particuliers   19968 non-null  float64
 14  tp_neige_precipitation_solide               19968 non-null  float64
 15  tp_phenomenes_recents_derniere_heure        19968 non-null  float64
 16  tp_pluie_ou_bruine                          19968 non-null  float64
 17  tp_sans_precipitation_visibilite_ou_nuages  19968 non-null  float64
 18  tp_tempete_poussiere_chasse_neige           19968 non-null  float64
 19  tp_temps_inconnu                            19968 non-null  float64
dtypes: float64(18), str(2)
memory usage: 3.0 MB

,date_semaine,code_dept,pression_mer,tendance_pression_3h,vent_direction,vent_vitesse,temperature_kelvin,humidite_relative,visibilite,pression_station,precipitation_3h,tp_averses_ou_orages,tp_brouillard,tp_brume_fumee_ou_phenomenes_particuliers,tp_neige_precipitation_solide,tp_phenomenes_recents_derniere_heure,tp_pluie_ou_bruine,tp_sans_precipitation_visibilite_ou_nuages,tp_tempete_poussiere_chasse_neige,tp_temps_inconnu
0,2021-S01,01,101586.607143,13.928571,258.750000,1.875000,272.803571,87.767857,9165.000000,98595.535714,-0.6,0.0,0.0,6.0,0.0,3.0,1.0,46.0,0.0,0.0
1,2021-S01,02,101806.250000,19.464286,163.035714,2.142857,274.617857,88.946429,11832.142857,100615.357143,-1.1,0.0,2.0,4.0,0.0,0.0,4.0,46.0,0.0,0.0
2,2021-S01,03,101656.428571,16.250000,206.071429,1.339286,272.644643,82.392857,11617.857143,97613.035714,1.4,0.0,1.0,10.0,2.0,0.0,0.0,43.0,0.0,0.0
3,2021-S01,04,101740.000000,11.071429,106.071429,3.214286,271.585714,59.089286,18886.250000,90856.785714,0.5,0.0,0.0,0.0,3.0,0.0,0.0,53.0,0.0,0.0
4,2021-S01,05,101740.000000,11.071429,106.071429,3.214286,271.585714,59.089286,18886.250000,90856.785714,0.5,0.0,0.0,0.0,3.0,0.0,0.0,53.0,0.0,0.0
5,2021-S01,06,101048.571429,10.000000,280.892857,3.892857,279.242857,67.125000,41569.464286,100728.750000,4.9,1.0,0.0,1.0,0.0,5.0,0.0,49.0,0.0,0.0
6,2021-S01,07,101403.214286,12.500000,72.678571,4.660714,275.457143,72.107143,18030.714286,100479.285714,2.7,0.0,0.0,0.0,2.0,0.0,1.0,53.0,0.0,0.0
7,2021-S01,08,101806.250000,19.464286,163.035714,2.142857,274.617857,88.946429,11832.142857,100615.357143,-1.1,0.0,2.0,4.0,0.0,0.0,4.0,46.0,0.0,0.0
8,2021-S01,09,101551.428571,16.607143,70.535714,0.446429,272.439286,88.696429,12063.392857,96440.000000,18.0,0.0,1.0,3.0,11.0,0.0,0.0,41.0,0.0,0.0
9,2021-S01,10,101781.428571,19.107143,186.607143,1.571429,274.235714,88.607143,9799.464286,100302.500000,2.7,0.0,1.0,17.0,0.0,0.0,8.0,30.0,0.0,0.0

In [10]:
#exporte lle data frame corrigé
df_meteo.to_csv("../data/final_metropole/final_meteo_hebdo_clean_96v2.csv", index=False, encoding='utf-8')

In [11]:
#vérifie que le fichier a bien été créé et qu'il contient les bonnes colonnes
final_meteo_hebdo_clean_96_v2= pd.read_csv("../data/final_metropole/final_meteo_hebdo_clean_96v2.csv")

final_meteo_hebdo_clean_96_v2.info()

final_meteo_hebdo_clean_96_v2.head(10)

final_meteo_hebdo_clean_96_v2['date_semaine'].unique()

<class 'pandas.DataFrame'>
RangeIndex: 19968 entries, 0 to 19967
Data columns (total 20 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   date_semaine                                19968 non-null  str
 1   code_dept                                   19968 non-null  str
 2   pression_mer                                19968 non-null  float64
 3   tendance_pression_3h                        19968 non-null  float64
 4   vent_direction                              19968 non-null  float64
 5   vent_vitesse                                19968 non-null  float64
 6   temperature_kelvin                          19968 non-null  float64
 7   humidite_relative                           19968 non-null  float64
 8   visibilite                                  19968 non-null  float64
 9   pression_station                            19968 non-null  float64
 10  precipitation_3h                            19968 non-null  float64
 11  tp_averses_ou_orages                        19968 non-null  float64
 12  tp_brouillard                               19968 non-null  float64
 13  tp_brume_fumee_ou_phenomenes_particuliers   19968 non-null  float64
 14  tp_neige_precipitation_solide               19968 non-null  float64
 15  tp_phenomenes_recents_derniere_heure        19968 non-null  float64
 16  tp_pluie_ou_bruine                          19968 non-null  float64
 17  tp_sans_precipitation_visibilite_ou_nuages  19968 non-null  float64
 18  tp_tempete_poussiere_chasse_neige           19968 non-null  float64
 19  tp_temps_inconnu                            19968 non-null  float64
dtypes: float64(18), str(2)
memory usage: 3.0 MB

<StringArray>
['2021-S01', '2021-S02', '2021-S03', '2021-S04', '2021-S05', '2021-S06',
 '2021-S07', '2021-S08', '2021-S09', '2021-S10',
 ...
 '2024-S43', '2024-S44', '2024-S45', '2024-S46', '2024-S47', '2024-S48',
 '2024-S49', '2024-S50', '2024-S51', '2024-S52']
Length: 208, dtype: str