In [110]:
#import des librairies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [111]:
df_effectifs = pd.read_csv(
    "../data/raw/Sante/effectifs.csv", sep=';', 
)
df_effectifs.head()

,annee,patho_niv1,patho_niv2,patho_niv3,top,cla_age_5,sexe,region,dept,Ntop,Npop,prev,Niveau prioritaire,libelle_classe_age,libelle_sexe,tri
0,2020,Maladies psychiatriques,Troubles psychotiques,Troubles psychotiques,PSY_PSC_IND,50-54,2,1,971,280.0,17040,1.643,"2,3",de 50 à 54 ans,femmes,48.0
1,2020,Maladies psychiatriques,Troubles psychotiques,Troubles psychotiques,PSY_PSC_IND,50-54,2,3,999,50.0,6090,0.771,"2,3",de 50 à 54 ans,femmes,48.0
2,2020,Maladies psychiatriques,Troubles psychotiques,Troubles psychotiques,PSY_PSC_IND,50-54,2,4,974,390.0,32630,1.205,"2,3",de 50 à 54 ans,femmes,48.0
3,2020,Maladies psychiatriques,Troubles psychotiques,Troubles psychotiques,PSY_PSC_IND,50-54,2,11,77,350.0,48230,0.732,"2,3",de 50 à 54 ans,femmes,48.0
4,2020,Maladies psychiatriques,Troubles psychotiques,Troubles psychotiques,PSY_PSC_IND,50-54,2,11,91,400.0,43370,0.927,"2,3",de 50 à 54 ans,femmes,48.0

In [112]:
df_effectifs.info()

<class 'pandas.DataFrame'>
RangeIndex: 5796000 entries, 0 to 5795999
Data columns (total 16 columns):
 #   Column              Dtype
---  ------              -----
 0   annee               int64
 1   patho_niv1          str
 2   patho_niv2          str
 3   patho_niv3          str
 4   top                 str
 5   cla_age_5           str
 6   sexe                int64
 7   region              int64
 8   dept                str
 9   Ntop                float64
 10  Npop                int64
 11  prev                float64
 12  Niveau prioritaire  str
 13  libelle_classe_age  str
 14  libelle_sexe        str
 15  tri                 float64
dtypes: float64(3), int64(4), str(9)
memory usage: 707.5 MB

In [113]:
#Quelles sont les valeurs uniques pour les pathologies de niveau 1
print(df_effectifs["patho_niv1"].unique())

<StringArray>
[                                                                                         'Maladies psychiatriques',
                                                           'Maladies respiratoires chroniques (hors mucoviscidose)',
                                                                'Maladies inflammatoires ou rares ou infection VIH',
                                                                                           'Maladies neurologiques',
 'Pas de pathologie repérée, traitement, maternité, hospitalisation ou traitement antalgique ou anti-inflammatoire',
                                                                                   'Total consommants tous régimes',
                                                                                                          'Cancers',
                                                                                                          'Diabète',
                                                              'Traitements du risque vasculaire (hors pathologies)',
                                                                             'Maternité (avec ou sans pathologies)',
                                                                                  'Maladies cardioneurovasculaires',
                                                             'Maladies du foie ou du pancréas (hors mucoviscidose)',
                  'Hospitalisations hors pathologies repérées (avec ou sans pathologies, traitements ou maternité)',
                                                                          'Insuffisance rénale chronique terminale',
                                                                      'Traitements psychotropes (hors pathologies)',
                                                                                    'Hospitalisation pour Covid-19',
    'Traitements antalgiques ou anti-inflammatoires (hors pathologies, traitements, maternité ou hospitalisations)',
                                                  'Affections de longue durée (dont 31 et 32) pour d'autres causes']
Length: 18, dtype: str

Le fichier est assez lourd, pour ne pas avoir à manipuler tout les données qui ne seront pas utiles pour notre projet, je commence par faire 2 df differentes, un avec uniquement les maladies respiratoires chroniques, et l'autre qui contient les hospitalisations pour Covid-19, Traitement antalgique ou anti-inflammatoire et Cancers

In [114]:
# 1. Définir les 4 catégories à explorer
pathologies = [
    "Maladies respiratoires chroniques (hors mucoviscidose)",
    "Hospitalisation pour Covid-19",
    "Traitements antalgiques ou anti-inflammatoires (hors pathologies, traitements, maternité ou hospitalisations)",
    "Cancers"
]
pathologie_respi = [
    "Maladies respiratoires chroniques (hors mucoviscidose)"
]

#creation nouvelle df filtré pour 4 categories selectionnées
df_effectifs_filtre_patho = df_effectifs[
    df_effectifs["patho_niv1"].isin(pathologies)
].copy()



#creation nouvelle df filtré pour les maladies respiratoires uniquement

df_respi = df_effectifs[
    df_effectifs["patho_niv1"].isin(pathologie_respi)
]

In [115]:
#Exportation des 2 fichiers
df_effectifs_filtre_patho.to_csv("df_effectifs_filtre_patho.csv", sep=",", index=False)

df_respi.to_csv("df_respi", sep=",", index=False)

Je continue le preprocessing avec df_respi

la catégorie "Maladie respiratoires chroniques" regroupe plusieurs maladies respiratoires chroniques : elle ne permet pas d’isoler précisément l’asthme, l’allergie ou la bronchiolite.

In [116]:
print("Original :", df_effectifs.shape)

print("Respi:", df_respi.shape)

df_respi.head(5)

Original : (5796000, 16)
Respi: (75600, 16)

,annee,patho_niv1,patho_niv2,patho_niv3,top,cla_age_5,sexe,region,dept,Ntop,Npop,prev,Niveau prioritaire,libelle_classe_age,libelle_sexe,tri
1259,2020,Maladies respiratoires chroniques (hors mucovi...,Maladies respiratoires chroniques (hors mucovi...,Maladies respiratoires chroniques (hors mucovi...,RES_CAT_EXC,00-04,1,2,972,470.0,8310,5.679,"1,2,3",de 0 à 4 ans,hommes,10.0
1260,2020,Maladies respiratoires chroniques (hors mucovi...,Maladies respiratoires chroniques (hors mucovi...,Maladies respiratoires chroniques (hors mucovi...,RES_CAT_EXC,00-04,1,6,999,90.0,8130,1.046,"1,2,3",de 0 à 4 ans,hommes,10.0
1261,2020,Maladies respiratoires chroniques (hors mucovi...,Maladies respiratoires chroniques (hors mucovi...,Maladies respiratoires chroniques (hors mucovi...,RES_CAT_EXC,00-04,1,11,92,3080.0,52210,5.899,"1,2,3",de 0 à 4 ans,hommes,10.0
1262,2020,Maladies respiratoires chroniques (hors mucovi...,Maladies respiratoires chroniques (hors mucovi...,Maladies respiratoires chroniques (hors mucovi...,RES_CAT_EXC,00-04,1,11,95,2370.0,45900,5.168,"1,2,3",de 0 à 4 ans,hommes,10.0
1263,2020,Maladies respiratoires chroniques (hors mucovi...,Maladies respiratoires chroniques (hors mucovi...,Maladies respiratoires chroniques (hors mucovi...,RES_CAT_EXC,00-04,1,11,999,21150.0,393510,5.373,"1,2,3",de 0 à 4 ans,hommes,10.0

In [117]:
#verification des souscategories des pathologies

colonnes = ["patho_niv1", "patho_niv2", "patho_niv3", "top"]

for col in colonnes:
    print(f"\n--- {col} ---")
    print(df_respi[col].value_counts(dropna=False))

--- patho_niv1 ---
patho_niv1
Maladies respiratoires chroniques (hors mucoviscidose)    75600
Name: count, dtype: int64

--- patho_niv2 ---
patho_niv2
Maladies respiratoires chroniques (hors mucoviscidose)    75600
Name: count, dtype: int64

--- patho_niv3 ---
patho_niv3
Maladies respiratoires chroniques (hors mucoviscidose)    75600
Name: count, dtype: int64

--- top ---
top
RES_CAT_EXC    75600
Name: count, dtype: int64

In [118]:
df_respi[colonnes].drop_duplicates()

,patho_niv1,patho_niv2,patho_niv3,top
1259,Maladies respiratoires chroniques (hors mucovi...,Maladies respiratoires chroniques (hors mucovi...,Maladies respiratoires chroniques (hors mucovi...,RES_CAT_EXC

Entre les 4 colonnes patho_niv1, patho_niv2, patho_niv3 et top les informations sont redontandtes, je vais garder la categorie "top" qui contient le code et creer un colonne "pathologie" et supprimer le reste

libellées classe d_age et libelle_sexe car ils sont redondant et reconstituables.

Je garde la colonne "region" à cet etape

In [119]:
#creation d'un copy de travail
df_respi_travail = df_respi.copy()

#creation d'une colonnne "pathologie"
df_respi_travail["pathologie"] = "Maladie_Respi_Chronique"
#Supresson des colonnes: "libelle_classe_age","libelle_sexe","patho_niv1","patho_niv2", "patho_niv3", "Niveau prioritaire", "tri"
df_respi_travail = df_respi_travail.drop(columns=["libelle_classe_age", "libelle_sexe", "patho_niv1", "patho_niv2", "patho_niv3","Niveau prioritaire", "tri" ])

display(df_respi_travail.info())
display(df_respi_travail.head(5))

<class 'pandas.DataFrame'>
Index: 75600 entries, 1259 to 5759926
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   annee       75600 non-null  int64
 1   top         75600 non-null  str
 2   cla_age_5   75600 non-null  str
 3   sexe        75600 non-null  int64
 4   region      75600 non-null  int64
 5   dept        75600 non-null  str
 6   Ntop        75421 non-null  float64
 7   Npop        75600 non-null  int64
 8   prev        75421 non-null  float64
 9   pathologie  75600 non-null  str
dtypes: float64(2), int64(4), str(4)
memory usage: 6.3 MB

None

,annee,top,cla_age_5,sexe,region,dept,Ntop,Npop,prev,pathologie
1259,2020,RES_CAT_EXC,00-04,1,2,972,470.0,8310,5.679,Maladie_Respi_Chronique
1260,2020,RES_CAT_EXC,00-04,1,6,999,90.0,8130,1.046,Maladie_Respi_Chronique
1261,2020,RES_CAT_EXC,00-04,1,11,92,3080.0,52210,5.899,Maladie_Respi_Chronique
1262,2020,RES_CAT_EXC,00-04,1,11,95,2370.0,45900,5.168,Maladie_Respi_Chronique
1263,2020,RES_CAT_EXC,00-04,1,11,999,21150.0,393510,5.373,Maladie_Respi_Chronique

Supprimer les annees pas retenus, garder 2021 -2024

In [120]:
# Garder uniquement les années choisies
df_annees = df_respi_travail["annee"].isin([2021, 2022, 2023, 2024])

df_respi_travail = df_respi_travail.loc[df_annees].copy()

# Vérifier les années restantes
print(sorted(df_respi_travail["annee"].unique()))

[np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]

Comme le jeu de données contient trois niveaux d’agrégation territoriale : départemental, régional et national. Les codes dept = 999 et region ≠ 99 semblent correspondre aux totaux régionaux, tandis que dept = 999 et region = 99 représenteraient le total national (à confirmer dans la documentation). Il faut distinguer ces niveaux lors des analyses pour éviter les doubles comptages.

In [121]:
#1. Examiner les couples département–région: afficher chaque association departement-region avec le nombre de ligne correspondant

# Copie pour les contrôles ; codes conservés comme chaînes
df_controle = df_respi_travail.copy()

for col in ["dept", "region"]:
    df_controle[col] = df_controle[col].astype("string").str.strip()  #transformer en texte et retierer les espaces eventuelles

couples = (
    df_controle.groupby(["dept", "region"], dropna=False)       #rassemble les lignes ayant le même couple département–région, on garde les lignes avec les NA
    .size()                                                     #compte les lignes de chaque groupes
    .reset_index(name="nombre_lignes")                          #resultats en DF avec 3 colonnes dept, region et nombre_lignes
)

display(couples.sort_values(["region", "dept"]))

# Examiner séparément les lignes supposées régionales et nationales
display(couples.loc[couples["dept"]=="999"])

    dept region  nombre_lignes
96   971      1            252
101  999      1            252
75    75     11            252
77    77     11            252
78    78     11            252
..   ...    ...            ...
117  999     93            252
28    2A     94            252
29    2B     94            252
118  999     94            252
119  999     99            252

[120 rows x 3 columns]

    dept region  nombre_lignes
101  999      1            252
102  999     11            252
103  999      2            252
104  999     24            252
105  999     27            252
106  999     28            252
107  999      3            252
108  999     32            252
109  999      4            252
110  999     44            252
111  999     52            252
112  999     53            252
113  999      6            252
114  999     75            252
115  999     76            252
116  999     84            252
117  999     93            252
118  999     94            252
119  999     99            252

La conclusion : les lignes dept = 999 doivent être mises à part pour une analyse départementale.

Verifications

In [122]:
#  chaque département est-il toujours associé à une seule région  ?


departements = df_controle.loc[
    df_controle["dept"].notna()         #code de departement est renseigné et
    & (df_controle["dept"] != "999")     #le code département est différent de "999"
].copy()

regions_par_departement = (
    departements.groupby("dept")
    .agg(
        nombre_regions=("region", lambda s: s.nunique(dropna=False)),           #combien de valeurs différentes apparaissent dans region
        codes_region=("region", lambda s: s.drop_duplicates().tolist())         #la liste de ces valeurs, sans répétition
    )
)

# Une table vide signifie qu'aucun département n'a plusieurs régions
display(
    regions_par_departement.loc[
        regions_par_departement["nombre_regions"] != 1
    ]
)

# Repérer aussi les départements sans région ou associés à "99"
display(
    departements.loc[
        departements["region"].isna()
        | (departements["region"] == "99"),     #departements avec un region manquant ou egale à 99
        ["dept", "region"]
    ].drop_duplicates()
)

Empty DataFrame
Columns: [nombre_regions, codes_region]
Index: []

Empty DataFrame
Columns: [dept, region]
Index: []

compare les totaux publiés aux sommes des départements, séparément pour chaque année

In [123]:
# Selectionner tous age et tous sexe
base = df_controle.loc[
    (df_controle["cla_age_5"].astype("string") == "tsage")       #selectionner tous age et
    & (df_controle["sexe"].astype("string") == "9")              #tout sexe
].copy()


#Vérifier qu’une même observation n’apparaît pas plusieurs fois
cles = ["annee", "region" , "dept"]


doublons = base.duplicated(cles, keep=False)
display(base.loc[doublons])

if doublons.any():
    raise ValueError("Des doublons doivent être examinés avant de calculer les sommes.")

Empty DataFrame
Columns: [annee, top, cla_age_5, sexe, region, dept, Ntop, Npop, prev, pathologie]
Index: []

La combinaison année + région + département est unique. Le tableu vide signifie que aucun doublon n'a ete trouvé

In [124]:
#Separer les 3 niveux territorieaux: les trois tables sont séparées pour que les totaux publiés ne soient jamais inclus dans la somme des départements.

# Lignes départementales
details = base.loc[
    base["dept"].notna()
    & (base["dept"] != "999")
    & base["region"].notna()
    & (base["region"] != "99")
].copy()

# Totaux régionaux supposés
totaux_regionaux = base.loc[
    (base["dept"] == "999")
    & base["region"].notna()
    & (base["region"] != "99")
].copy()

# Total national supposé
total_national = base.loc[
    (base["dept"] == "999")
    & (base["region"] == "99")
].copy()

In [125]:
#  Additionner les départements pour chaque année et région
sommes_regions = (
    details.groupby(["annee", "region"])[["Ntop", "Npop"]]
    .agg(lambda colonne: colonne.sum(skipna=False))
    .reset_index()
)

display(sommes_regions)

    annee region      Ntop      Npop
0    2021      1   18480.0    393330
1    2021     11  574110.0  12599140
2    2021      2   15360.0    368880
3    2021     24  135010.0   2590760
4    2021     27  148220.0   2788190
..    ...    ...       ...       ...
67   2024     75  431870.0   6134910
68   2024     76  406520.0   6131500
69   2024     84  448260.0   8094330
70   2024     93  342540.0   5401550
71   2024     94   22760.0    316760

[72 rows x 4 columns]

In [126]:
#  Mettre les sommes et les totaux publiés côte à côte
controle_regions = sommes_regions.merge(
    totaux_regionaux[["annee", "region", "Ntop", "Npop"]],
    on=["annee", "region"],
    how="outer",
    suffixes=("_somme_departements", "_publie"),    #distingues les sommes calculés des valeurs publiés
    validate="one_to_one"                           #vérifie qu’il existe au maximum une ligne de chaque côté pour chaque année–région
)

# Calculer les differences

controle_regions["ecart_Ntop"] = (
    controle_regions["Ntop_somme_departements"]
    - controle_regions["Ntop_publie"]
)

controle_regions["ecart_Npop"] = (
    controle_regions["Npop_somme_departements"]
    - controle_regions["Npop_publie"]
)

display(controle_regions)
controle_regions.info()

,annee,region,Ntop_somme_departements,Npop_somme_departements,Ntop_publie,Npop_publie,ecart_Ntop,ecart_Npop
0,2021,1,18480.0,393330,18480.0,393330,0.0,0
1,2021,11,574110.0,12599140,574110.0,12599120,0.0,20
2,2021,2,15360.0,368880,15360.0,368880,0.0,0
3,2021,24,135010.0,2590760,135010.0,2590760,0.0,0
4,2021,27,148220.0,2788190,148210.0,2788190,10.0,0
...,...,...,...,...,...,...,...,...
67,2024,75,431870.0,6134910,431870.0,6134900,0.0,10
68,2024,76,406520.0,6131500,406500.0,6131500,20.0,0
69,2024,84,448260.0,8094330,448260.0,8094340,0.0,-10
70,2024,93,342540.0,5401550,342540.0,5401550,0.0,0
71,2024,94,22760.0,316760,22810.0,317210,-50.0,-450

<class 'pandas.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   annee                    72 non-null     int64
 1   region                   72 non-null     string
 2   Ntop_somme_departements  72 non-null     float64
 3   Npop_somme_departements  72 non-null     int64
 4   Ntop_publie              72 non-null     float64
 5   Npop_publie              72 non-null     int64
 6   ecart_Ntop               72 non-null     float64
 7   ecart_Npop               72 non-null     int64
dtypes: float64(3), int64(4), string(1)
memory usage: 4.6 KB

In [127]:
#verification si il y a des lignes non calculables

colonnes_valeurs = [
    "Ntop_somme_departements", "Ntop_publie",
    "Npop_somme_departements", "Npop_publie"
]

lignes_na = controle_regions.loc[
    controle_regions[colonnes_valeurs].isna().any(axis=1)
]

display(lignes_na)

Empty DataFrame
Columns: [annee, region, Ntop_somme_departements, Npop_somme_departements, Ntop_publie, Npop_publie, ecart_Ntop, ecart_Npop]
Index: []

pas de lignes avec des NA, tout est calculable

In [128]:
#afficher les valeurs non nulles 

lignes_ecarts = controle_regions.loc[
    (controle_regions["ecart_Ntop"].notna()
        & (controle_regions["ecart_Ntop"] != 0))
    |(controle_regions["ecart_Npop"].notna()
        & (controle_regions["ecart_Npop"] != 0)
    )
]

display(lignes_ecarts.sort_values(["annee", "region"])) 

lignes_ecarts.info()

,annee,region,Ntop_somme_departements,Npop_somme_departements,Ntop_publie,Npop_publie,ecart_Ntop,ecart_Npop
1,2021,11,574110.0,12599140,574110.0,12599120,0.0,20
4,2021,27,148220.0,2788190,148210.0,2788190,10.0,0
5,2021,28,207890.0,3349330,207900.0,3349330,-10.0,0
7,2021,32,369460.0,5996760,369460.0,5996750,0.0,10
9,2021,44,297500.0,5335930,297490.0,5335920,10.0,10
10,2021,52,189970.0,3919390,189960.0,3919380,10.0,10
11,2021,53,189740.0,3446250,189740.0,3446240,0.0,10
13,2021,75,365950.0,6168180,365940.0,6168160,10.0,20
14,2021,76,344440.0,6141180,344440.0,6141170,0.0,10
15,2021,84,377890.0,8191240,377900.0,8191240,-10.0,0
16,2021,93,296610.0,5435790,296600.0,5435790,10.0,0
17,2021,94,18500.0,319350,18560.0,320010,-60.0,-660
21,2022,24,144340.0,2605560,144350.0,2605550,-10.0,10
22,2022,27,157550.0,2792740,157550.0,2792730,0.0,10
23,2022,28,222640.0,3363770,222640.0,3363760,0.0,10
25,2022,32,392010.0,5996480,392000.0,5996480,10.0,0
27,2022,44,317600.0,5340280,317590.0,5340270,10.0,10
29,2022,53,202470.0,3486110,202480.0,3486110,-10.0,0
31,2022,75,393460.0,6218940,393450.0,6218920,10.0,20
32,2022,76,370420.0,6192400,370410.0,6192400,10.0,0
33,2022,84,408780.0,8222260,408780.0,8222270,0.0,-10
35,2022,94,20820.0,318940,20860.0,319520,-40.0,-580
37,2023,11,627110.0,12181340,627090.0,12181330,20.0,10
39,2023,24,148790.0,2536810,148780.0,2536800,10.0,10
40,2023,27,163120.0,2730440,163100.0,2730440,20.0,0
41,2023,28,228730.0,3288450,228730.0,3288460,0.0,-10
43,2023,32,399850.0,5855050,399850.0,5855040,0.0,10
45,2023,44,328050.0,5234380,328040.0,5234390,10.0,-10
46,2023,52,209570.0,3878720,209580.0,3878730,-10.0,-10
47,2023,53,206820.0,3432590,206810.0,3432590,10.0,0
49,2023,75,406330.0,6112260,406330.0,6112230,0.0,30
50,2023,76,383290.0,6098950,383270.0,6098930,20.0,20
51,2023,84,424770.0,8063070,424760.0,8063060,10.0,10
53,2023,94,21300.0,313140,21360.0,313670,-60.0,-530
57,2024,24,158170.0,2541850,158150.0,2541840,20.0,10
58,2024,27,172200.0,2729880,172210.0,2729870,-10.0,10
61,2024,32,423680.0,5854990,423680.0,5855000,0.0,-10
63,2024,44,348190.0,5238970,348200.0,5238960,-10.0,10
64,2024,52,226170.0,3900020,226160.0,3900020,10.0,0
65,2024,53,218980.0,3454970,218970.0,3454960,10.0,10
67,2024,75,431870.0,6134910,431870.0,6134900,0.0,10
68,2024,76,406520.0,6131500,406500.0,6131500,20.0,0
69,2024,84,448260.0,8094330,448260.0,8094340,0.0,-10
71,2024,94,22760.0,316760,22810.0,317210,-50.0,-450

<class 'pandas.DataFrame'>
Index: 44 entries, 1 to 71
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   annee                    44 non-null     int64
 1   region                   44 non-null     string
 2   Ntop_somme_departements  44 non-null     float64
 3   Npop_somme_departements  44 non-null     int64
 4   Ntop_publie              44 non-null     float64
 5   Npop_publie              44 non-null     int64
 6   ecart_Ntop               44 non-null     float64
 7   ecart_Npop               44 non-null     int64
dtypes: float64(3), int64(4), string(1)
memory usage: 3.1 KB

Sur 72 comparaisons région–année, 44 présentent un écart sur Ntop et/ou Npop entre la somme départementale et le total régional publié. L’origine de ces écarts n’a pas été déterminée. La suite de l’analyse utilise uniquement les observations départementales.

Pour la suite - creation de df_respi_departementale en gardeant la colonne region pour les regroupements eventuelles

In [129]:
df = df_respi_travail.copy()

# Harmoniser les codes territoriaux sans remplacer les NA
for col in ["dept", "region"]:
    df[col] = df[col].astype("string").str.strip()


# Attribuer un niveau territorial à chaque ligne
df["niveau"] = "a_verifier"

region_connue = df["region"].notna() & (df["region"] != "99")

#on donne la valeur "departement" aux lignes ou le departement est connu, pas egale à 999 et region est connu
df.loc[
    df["dept"].notna() & (df["dept"] !="999") & region_connue,
    "niveau"
] = "departements"

#on donne la valeur "regions" aux lignes ou le departement est  à 999 et region est connu
df.loc[
    df["dept"].eq("999") & region_connue,
    "niveau"
] = "regions"

#etiquette national
df.loc[
    (df["dept"] == "999") & (df["region"] == "99"),
    "niveau"
] = "national"

# Séparer les niveaux et exporter les CSV
from pathlib import Path
dossier = Path("exports_effectifs")
dossier.mkdir(exist_ok=True)

In [130]:
# Séparer les niveaux et exporter les CSV
# Séparer les données en 4 DataFrames
df_respi_dept = df[df["niveau"] == "departements"].copy()
df_respi_region = df[df["niveau"] == "regions"].copy()
df_respi_national = df[df["niveau"] == "national"].copy()
df_respi_a_verifier = df[df["niveau"] == "a_verifier"].copy()

display(df_respi_dept.head(5))
display(df_respi_region.head(5))
display(df_respi_national.head(5))
display(df_respi_a_verifier.head(5))


#exporter les csv

df_respi_dept.to_csv("respi_dept.csv", index=False, sep=",")
df_respi_region.to_csv("respi_region.csv", index=False, sep=",")
df_respi_national.to_csv("respi_national.csv", index=False, sep=",")
df_respi_a_verifier.to_csv("respi_a_verifier.csv", index=False, sep=",")

,annee,top,cla_age_5,sexe,region,dept,Ntop,Npop,prev,pathologie,niveau
38778,2024,RES_CAT_EXC,85-89,1,32,02,700.0,3770,18.503,Maladie_Respi_Chronique,departements
38780,2024,RES_CAT_EXC,85-89,1,44,10,350.0,2620,13.354,Maladie_Respi_Chronique,departements
38781,2024,RES_CAT_EXC,85-89,1,44,52,280.0,1770,15.971,Maladie_Respi_Chronique,departements
38782,2024,RES_CAT_EXC,85-89,1,44,67,1270.0,8750,14.485,Maladie_Respi_Chronique,departements
38783,2024,RES_CAT_EXC,85-89,1,44,08,390.0,2190,17.986,Maladie_Respi_Chronique,departements

,annee,top,cla_age_5,sexe,region,dept,Ntop,Npop,prev,pathologie,niveau
38777,2024,RES_CAT_EXC,85-89,1,28,999,4470.0,27770,16.100,Maladie_Respi_Chronique,regions
38779,2024,RES_CAT_EXC,85-89,1,32,999,6710.0,37310,17.975,Maladie_Respi_Chronique,regions
38791,2024,RES_CAT_EXC,85-89,1,75,999,8720.0,60560,14.398,Maladie_Respi_Chronique,regions
38795,2024,RES_CAT_EXC,85-89,1,76,999,8270.0,56370,14.670,Maladie_Respi_Chronique,regions
38801,2024,RES_CAT_EXC,85-89,1,93,999,7050.0,48920,14.405,Maladie_Respi_Chronique,regions

,annee,top,cla_age_5,sexe,region,dept,Ntop,Npop,prev,pathologie,niveau
38803,2024,RES_CAT_EXC,85-89,1,99,999,78060.0,547950,14.246,Maladie_Respi_Chronique,national
38841,2024,RES_CAT_EXC,85-89,2,99,999,96740.0,865950,11.171,Maladie_Respi_Chronique,national
39037,2024,RES_CAT_EXC,95et+,1,99,999,9680.0,71430,13.550,Maladie_Respi_Chronique,national
39077,2024,RES_CAT_EXC,95et+,2,99,999,24950.0,243160,10.262,Maladie_Respi_Chronique,national
39155,2024,RES_CAT_EXC,tsage,1,99,999,2031930.0,32440780,6.263,Maladie_Respi_Chronique,national

Empty DataFrame
Columns: [annee, top, cla_age_5, sexe, region, dept, Ntop, Npop, prev, pathologie, niveau]
Index: []

Verification le df_respi_dept

In [131]:
df_respi_dept.info()

<class 'pandas.DataFrame'>
Index: 25452 entries, 38778 to 5709338
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   annee       25452 non-null  int64
 1   top         25452 non-null  str
 2   cla_age_5   25452 non-null  str
 3   sexe        25452 non-null  int64
 4   region      25452 non-null  string
 5   dept        25452 non-null  string
 6   Ntop        25418 non-null  float64
 7   Npop        25452 non-null  int64
 8   prev        25418 non-null  float64
 9   pathologie  25452 non-null  str
 10  niveau      25452 non-null  str
dtypes: float64(2), int64(3), str(4), string(2)
memory usage: 2.3 MB

In [132]:
df_respi_dept.isna().sum()

annee          0
top            0
cla_age_5      0
sexe           0
region         0
dept           0
Ntop          34
Npop           0
prev          34
pathologie     0
niveau         0
dtype: int64

In [133]:
df_respi_dept.nunique()

annee             4
top               1
cla_age_5        21
sexe              3
region           18
dept            101
Ntop           1727
Npop           7731
prev          11233
pathologie        1
niveau            1
dtype: int64

In [134]:
print(df_respi_dept["dept"].unique().tolist())

['02', '10', '52', '67', '08', '44', '49', '53', '85', '40', '47', '86', '12', '30', '65', '15', '42', '63', '69', '07', '2A', '971', '972', '973', '77', '91', '92', '95', '28', '21', '58', '71', '27', '88', '72', '56', '16', '33', '64', '79', '31', '32', '01', '26', '73', '05', '75', '93', '36', '45', '89', '90', '76', '80', '55', '35', '17', '81', '82', '09', '38', '43', '83', '974', '976', '78', '18', '37', '70', '51', '54', '57', '19', '24', '34', '74', '13', '2B', '39', '59', '87', '48', '04', '84', '50', '68', '29', '46', '66', '94', '14', '03', '06', '41', '60', '62', '22', '11', '25', '61', '23']

df_respi_dept contient encore des agregats tous age et tout sexe!

Est-ce qu'on veut faire un prediction globale par departement ou par departement et par classe d'age?

In [135]:
#Creation de df pour une prediciton globale: on garde tous age et tous sexe dans le df

df_respi_dept_global_metropole = df_respi_dept[
    (df_respi_dept["cla_age_5"] == "tsage") &
    (df_respi_dept["sexe"] == 9) &
    (~df_respi_dept["dept"].isin(["971", "972", "973", "974", "976"]))
].copy()

In [136]:
#verifier les valeurs manquantes
df_respi_dept_global_metropole[["Npop", "prev"]].isna().sum()

Npop    0
prev    0
dtype: int64

In [137]:
#verifier si j'ai bien une seule ligne par departement et par semaine
df_respi_dept_global_metropole.duplicated(subset=["dept", "annee"]).sum()

np.int64(0)

In [138]:
print(df_respi_dept_global_metropole.shape)
print(df_respi_dept_global_metropole[["Npop", "prev"]].isna().sum())

(384, 11)
Npop    0
prev    0
dtype: int64

le df_respi_dept_global_metropole est pret pour la jointure

In [139]:
#extraction fichier 
df_respi_dept_global_metropole.to_csv("respi_dept_global.csv", index=False, sep=",")

In [140]:
#creation de df pour une prediction par classe d'age

In [141]:
#df respi metropole (contient encore tranches d'ages et tous age")
df_respi_dept_metropole = df_respi_dept[
    (~df_respi_dept["dept"].isin(["971", "972", "973", "974", "976"]))
].copy()

print("Lignes du fichier df_respi_dept :", len(df_respi_dept))
print("Lignes métropolitaines :", len(df_respi_dept_metropole))

Lignes du fichier df_respi_dept : 25452
Lignes métropolitaines : 24192

Objectif est de vérifier si tu peux regrouper les 20 classes d'âge en 3 catégories (0-14, 15-64, 65+) et recalculer prev à partir de Ntop et Npop.

In [142]:
#je cree 3 categories d'ages

#df avec tous sexe et avec tous les categories d'age sauf tous age
df_age = df_respi_dept_metropole[
    (df_respi_dept_metropole["sexe"].astype(str) == "9") &
    (df_respi_dept_metropole["cla_age_5"] != "tsage")
].copy()

# Créer une nouvelle colonne pour les 3 catégories
df_age["age_groupe"] = "65+"

df_age.loc[df_age["cla_age_5"].isin(["00-04", "05-09", "10-14"]), "age_groupe"] = "0-14"

df_age.loc[df_age["cla_age_5"].isin([
    "15-19", "20-24", "25-29", "30-34", "35-39",
    "40-44", "45-49", "50-54", "55-59", "60-64"
]), "age_groupe"] = "15-64"

In [143]:
df_age[["Ntop", "Npop"]].isna().sum()

Ntop    0
Npop    0
dtype: int64

In [144]:
#regrouper et recalculer la prevalence dans le df avec les categories regroupées par an et par dept
df_respi_age = (
    df_age.groupby(["annee", "dept", "age_groupe"])[["Ntop", "Npop"]]
    .sum(min_count=1)
    .reset_index()
)

df_respi_age["prev"] = df_respi_age["Ntop"] / df_respi_age["Npop"] * 100

display(df_respi_age.head())

   annee dept age_groupe     Ntop    Npop      prev
0   2021   01       0-14   4330.0  119000  3.638655
1   2021   01      15-64  12970.0  399590  3.245827
2   2021   01        65+  11740.0  122010  9.622162
3   2021   02       0-14   3570.0   91960  3.882123
4   2021   02      15-64  16790.0  319770  5.250649

In [145]:
# Somme des 3 groupes par département et année
somme = df_respi_age.groupby(["annee", "dept"])[["Ntop", "Npop"]].sum()

# Effectifs officiels tous âges
total = df_respi_dept_metropole[
    (df_respi_dept_metropole["cla_age_5"] == "tsage") &
    (df_respi_dept_metropole["sexe"].astype(str) == "9")
].set_index(["annee", "dept"])[["Ntop", "Npop"]]

# Comparaison
display(somme - total)

            Ntop  Npop
annee dept
2021  01    10.0    30
      02     0.0   -10
      03    10.0    20
      04     0.0     0
      05     0.0    30
...          ...   ...
2024  91    10.0    20
      92     0.0     0
      93    10.0     0
      94    20.0     0
      95    20.0    30

[384 rows x 2 columns]